package catalog

// Commands is the catalog. The order is the order MCP tools register in,
// which is also the order the Markdown contract prints; the short CLI index
// regroups them by Group instead.
var Commands = []Command{
	{
		Name:      "login",
		MCPName:   "wanctl_login",
		Group:     GroupSession,
		IndexLine: "log in via the portal and save the token (no daemon)",
		Summary:   "Authenticate to a wanctl namespace through the portal",
		Desc:      "Authenticate THIS MCP session to a wanctl namespace via the team portal. Two-step OAuth flow: (1) call with NO argument first → returns a portal URL + a one-time code prompt the user needs to complete in their browser. (2) call again with the `code` the user pastes back → exchanges it for a namespace token bound ONLY to this MCP session (in HTTP mode) or this machine's wanctl config (in stdio mode). Multiple AI users sharing the same MCP server each log in independently — credentials are never shared across sessions.\n\nFAST RE-BIND: a successful login also returns a `rebind` credential. HTTP-MCP sessions are in-memory, so a relay restart or a dropped/re-initialized connection can surface 'LOGIN REQUIRED' mid-task even though the user is still authorized. When that happens, call wanctl_login(rebind=\"…\") with the credential you saved — it restores access INSTANTLY with no portal round-trip. Only fall back to the OAuth flow if you have no saved rebind credential.",
		Params: []Param{
			{Name: "code", Type: TypeString, CLI: "--code CODE", Desc: "The one-time code the user copied from the portal /enroll page. Omit on the first call."},
			{Name: "rebind", Type: TypeString, CLI: "-", MCPOnly: true, Desc: "A rebind credential returned by an earlier successful login in this conversation. Pass it to restore a lost session instantly without re-doing OAuth. Mutually exclusive with code."},
		},
		CLIExample: "wanctl login [--code CODE]",
		MCPExample: "wanctl_login{}  then  wanctl_login{\"code\":\"ABC123\"}",
		Errors: []Failure{
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpLogin",
	},
	{
		Name:      "status",
		IndexRank: 3,
		MCPName:   "wanctl_status",
		Group:     GroupDevice,
		IndexLine: "local agent and credential state, or a remote device's",
		Summary:   "Report login state, and on a device the agent's mode and version",
		Desc:      "Report whether this MCP session is logged in, what namespace it's bound to, and the controller fingerprint. Call this if a tool says 'login required' and you're not sure if a login already completed.",
		CLINote:   "Without --target this reads local state only and dials nothing. With one it asks that device for its agent mode and version, which is the quickest check that a device is reachable at all.",
		Params: []Param{
			{Name: "target", CLI: "--target NS/DEV", Type: TypeString, CLIOnly: true, Desc: "Ask this device for its agent mode and version instead of reporting local state. Omit it to read this machine only, which dials nothing."},
		},
		CLIExample: "wanctl status [--target NS/DEV]",
		MCPExample: "wanctl_status{}",
		Handler:    "mcpStatus",
	},
	{
		Name:       "logout",
		MCPName:    "wanctl_logout",
		Group:      GroupSession,
		IndexLine:  "stop the agent and forget the saved login",
		Summary:    "Clear the stored credentials",
		Desc:       "Clear this MCP session's stored credentials. Subsequent data tools (peers/exec/push/pull/logs) will require a fresh wanctl_login.",
		CLINote:    "On the CLI this also stops a background agent started by `wanctl start`, because a device that can no longer authenticate should not keep a dead connection open.",
		CLIExample: "wanctl logout",
		MCPExample: "wanctl_logout{}",
		Handler:    "mcpLogout",
	},
	{
		Name:       "peers",
		MCPName:    "wanctl_peers",
		Group:      GroupSession,
		IndexLine:  "list the devices this token can reach",
		Summary:    "List reachable devices and whether their identity is pinned",
		Desc:       "List devices currently reachable by the active controller token. Returns each stable device ID with its display label and whether this session has pinned its identity yet ('identity: pinned' / 'identity: unpinned'); structured content contains backward-compatible devices and aliases fields plus an identity map keyed by the canonical namespace/device. Purely a local lookup — it dials nothing. Use this FIRST when the user asks 'what devices are available' or before guessing a target.",
		CLIExample: "wanctl peers",
		MCPExample: "wanctl_peers{}",
		Errors: []Failure{
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpPeers",
	},
	{
		Name:      "pair",
		MCPName:   "wanctl_pair",
		Group:     GroupSession,
		IndexLine: "check trust, or get the URL the device owner approves",
		Summary:   "Check a device's trust state, or get the URL to pair with it",
		Desc:      "Check whether the target device already trusts this MCP session's controller identity, and if not, return the device-side pairing URL up front. On first contact this may instead return DEVICE IDENTITY CONFIRMATION REQUIRED; answer it yourself by calling wanctl_trust_server with the target and fingerprint from that result, then retry — no need to ask the user first. Once the server identity is pinned, returns '✓ already trusted' OR 'PAIRING REQUIRED' with a URL to relay VERBATIM to the user.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "<device>", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
		},
		CLIExample: "wanctl pair home-pc",
		MCPExample: "wanctl_pair{\"target\":\"home-pc\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "DEVICE IDENTITY MISMATCH", Means: "The device presented a different identity than the pinned one. Refused; nothing was sent. Report both fingerprints and stop \u2014 re-pinning is a human decision at a terminal."},
		},
		Handler: "mcpPair",
	},
	{
		Name:      "exec",
		MCPName:   "wanctl_exec",
		Group:     GroupControl,
		IndexLine: "run a command or script on a device (persistent shell)",
		Summary:   "Run a command, or a whole script, on a device",
		Desc: "Run a shell command, or a whole script, on a remote wanctl-enrolled device over the encrypted relay. Returns the device's stdout, stderr, and exit code. Pass EITHER 'command' (a one-liner) OR 'script' (multi-line source) — prefer 'script' for anything with a $, a quote inside a quote, or more than one statement, because a script is transported encoded and is never parsed by the device's shell. If the device hasn't paired this controller yet, the result is isError=true with a 'PAIRING REQUIRED' message that carries a URL — surface that URL VERBATIM to the user; do not paraphrase. If instead it says DEVICE IDENTITY CONFIRMATION REQUIRED, that is first contact: call wanctl_trust_server with the target and fingerprint it gives you and retry, without asking the user. To look at a file or change one line of it, use wanctl_read and wanctl_edit instead of cat/sed/echo here: they are native operations on the device, so they behave the same on every platform and nothing you pass is parsed by a shell." +
			"\n\nDEV LOOP — how these primitives fit together, because most work is a loop and not one call: wanctl_exec keeps a persistent shell per device, so cwd and exported variables survive between calls and you can cd once and stay there. Anything that does not return promptly — a dev server, a build, an install — belongs in wanctl_exec_async, which hands back a job_id immediately; follow it with wanctl_exec_poll until state is done, and the server keeps running on the device meanwhile. To look at a file use wanctl_read and to change one use wanctl_edit, never cat/sed/echo through this tool: the file tools are native on the device, identical on every OS, and nothing you pass is parsed by a shell. Reach for wanctl_push_blob only for binaries or for a large file that does not exist on the device yet — it overwrites whole files and loses concurrent edits.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices. If exactly one device is online for this token, you may pass empty string."},
			{Name: "command", Type: TypeString, CLI: "<command...>", CLIDesc: "The command to run, given as the trailing arguments. It is SOURCE CODE for the device's shell (sh on Unix, powershell on Windows) and is parsed there, so a nested `powershell -Command \"...$x...\"` is parsed twice and loses its variables to the outer pass; wanctl warns when it sees that shape. Use --script instead of nesting an interpreter.", Desc: "A one-liner for the device's default shell (sh on Unix, powershell on Windows). WARNING: this string is SOURCE CODE for that shell and is parsed there. On Windows that means writing `powershell -Command \"...$x...\"` gets parsed TWICE — the outer shell expands $x to nothing and the inner script fails with a misleading 'term is not recognized'. Use 'script' instead of nesting an interpreter here."},
			{Name: "script", Type: TypeString, CLI: "--script <local-file>", CLIDesc: "Path to a script FILE on this machine. Its contents are sent base64-encoded and run on the device, so quoting and character-set rules do not apply: $, backticks, nested quotes and non-ASCII text all arrive literally. The interpreter comes from the extension (.ps1 → PowerShell, .sh or none → sh) unless --interp says otherwise. This is the CLI spelling of the MCP `script` argument, which carries the source itself rather than a path.", Desc: "Script SOURCE to run on the device (not a file path). Sent encoded, so quoting and character-set rules do not apply: $, backticks, nested quotes and non-ASCII text all arrive literally. Requires 'interp'. Use this for multi-statement work; it is the same single call as 'command'. Scripts over ~9KB must be pushed as a file and run by path instead."},
			{Name: "interp", Type: TypeString, CLI: "--interp powershell|sh", CLIDesc: "Override the interpreter --script would infer from the file extension: powershell | sh.", Desc: "Interpreter for 'script': 'powershell' for Windows devices, 'sh' for Unix/macOS/Android. Required when 'script' is set."},
			{Name: "cwd", Type: TypeString, CLI: "-", MCPOnly: true, Desc: "Working directory on the device for this command (also the policy scope)."},
			{Name: "oneshot", Type: TypeBool, CLI: "--oneshot", Desc: "Run in a fresh shell with no persistent session state. Default false — successive exec calls share cwd/env like a real terminal."},
			{Name: "elevate", Type: TypeBool, CLI: "--elevate", Desc: "Android only. Run with elevated privilege (uid 0 or the adb shell uid 2000) instead of the app sandbox the agent normally lives in. This is what makes `pm`, `am`, `input`, `screencap`, `dumpsys`, `settings`, `wm` and `svc` work at all — without it they fail with permission errors or empty output. Elevated commands need their OWN policy rule on the device; a device in bypass mode still refuses them until a human approves, so expect a 'PAIRING/approval' style rejection the first time."},
			{Name: "via", Type: TypeString, CLI: "--via su|adb", Desc: "Pin the elevation channel: 'su' (rooted device) or 'adb' (device's own wireless debugging). Default empty = let the device pick whichever is available. Naming an unavailable channel fails instead of quietly running unprivileged."},
		},
		CLINote:    "On the command line --target may be omitted when the first argument names a device, or when exactly one device is online. --script takes a path to a local file, not the source itself. Background jobs — the wanctl_exec_async and wanctl_exec_poll pair above — have no CLI spelling yet; from a terminal, background the command on the device instead.",
		CLIExample: "wanctl exec --target home-pc \"uname -a\"\n  wanctl exec --target home-pc --script ./setup.sh",
		MCPExample: "wanctl_exec{\"target\":\"home-pc\",\"command\":\"uname -a\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "DEVICE IDENTITY MISMATCH", Means: "The device presented a different identity than the pinned one. Refused; nothing was sent. Report both fingerprints and stop \u2014 re-pinning is a human decision at a terminal."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpExec",
	},
	{
		Name:      "read",
		MCPName:   "wanctl_read",
		Group:     GroupFiles,
		IndexLine: "print a line range of a text file on a device",
		Summary:   "Read a range of lines from a text file on a device",
		Desc:      "Read a range of lines from a text file on a remote wanctl-enrolled device. Use this instead of `wanctl_exec` with cat/head/sed/Get-Content whenever you want to LOOK at a file: it is performed natively on the device, so it behaves identically on Linux, macOS, Windows and Android, nothing is parsed by a shell, and the reply tells you exactly what you got — 'lines A-B of N', the file's size, and the sha256 OF THE WHOLE FILE. Save that sha256: passing it back as wanctl_edit's expected_sha256 is how you make sure you are patching the text you actually read. Reads at most 256 KiB of content per call, and always cuts on a line boundary: when the range is cut short the result says truncated=true and names the `offset` to continue from, so paging never loses or repeats a line. The one exception is a single line bigger than 256 KiB, which cannot be returned whole — the result names that line and tells you to read it with wanctl_exec (sed/cut) instead; do not page on, because the same line would come back every time. Errors: 'not a UTF-8 text file' means the file is binary — use wanctl_pull or wanctl_exec instead, do not retry. Same pairing/policy rules as wanctl_exec: 'PAIRING REQUIRED' carries a URL to relay VERBATIM to the user, 'DEVICE IDENTITY CONFIRMATION REQUIRED' means call wanctl_trust_server and retry, and 'read denied by device policy' means the device's owner has not granted read access to that path.",
		CLINote:   "The content goes to stdout and the trailer — line numbers, the whole file's sha256, whether the 256 KiB cap cut the range short — goes to stderr, so `wanctl read … > file` captures exactly the file content.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
			{Name: "path", Type: TypeString, CLI: "<path>", Required: true, Desc: "Absolute path on the target device. `~` is NOT expanded — spell the home directory out."},
			{Name: "offset", Type: TypeNumber, CLI: "--offset N", Desc: "1-based line number to start at. Default 1. Use this to page through a file that came back truncated."},
			{Name: "limit", Type: TypeNumber, CLI: "--limit N", Desc: "Maximum number of lines to return. Default 2000. The 256 KiB byte cap applies regardless."},
		},
		CLIExample: "wanctl read --target home-pc /etc/hosts --offset 1 --limit 200",
		MCPExample: "wanctl_read{\"target\":\"home-pc\",\"path\":\"/etc/hosts\",\"limit\":200}",
		Errors: []Failure{
			{Text: "not a UTF-8 text file", Means: "The file is binary. Use pull (or exec) instead; retrying read will not help."},
			{Text: "read denied by device policy", Means: "The device owner has not granted read access to that path."},
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "does not support read/edit; run `wanctl update`", Means: "The device is running a wanctl older than the file tools. Update it there, then retry."},
		},
		Handler: "mcpRead",
	},
	{
		Name:      "edit",
		MCPName:   "wanctl_edit",
		Group:     GroupFiles,
		IndexLine: "replace an exact string inside a file on a device",
		Summary:   "Replace a string inside a file on a device, atomically",
		Desc:      "Replace a string inside a text file on a remote device, in place. This is the tool for PATCHING a remote file: it is the exact-string edit you are used to locally, performed natively on the device, so no shell parses your text ($, backticks, quotes and newlines all arrive literally) and the rest of the file is preserved byte for byte — CRLF line endings stay CRLF, the file mode is kept, and the write is atomic (temp file + rename), so a reader never sees a half-written file. Prefer it over rewriting a whole file with wanctl_push_blob, which silently discards anything that changed since you last read the file.\n\nWORKFLOW: wanctl_read the file, copy its sha256 into expected_sha256 here, and pass enough surrounding text in `old` that it matches exactly once.\n\nREFUSALS (the file is left untouched every time — fix the input and retry, do not fall back to exec): 'old string not found' means your `old` does not appear, usually because of whitespace or indentation, so re-read the file rather than guessing; 'old string occurs N times' means you must add surrounding context to disambiguate, or pass all=true if you really do mean every occurrence; 'changed since it was read' means someone else wrote to the file — the message carries the file's CURRENT sha256, so re-read and redo the edit against the new text. Files over 8 MiB are refused. Policy: an edit is a WRITE on the device and needs the same grant as wanctl_push; a first edit on an unapproved path may wait for the device owner to approve it.",
		CLINote:   "--old-file and --new-file read the text from a local file, which is how a multi-line block gets through without fighting the shell over quoting. Giving both --old and --old-file is an error rather than a precedence rule.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
			{Name: "path", Type: TypeString, CLI: "<path>", Required: true, Desc: "Absolute path on the target device. `~` is NOT expanded."},
			{Name: "old", Type: TypeString, CLI: "--old STR | --old-file F", Required: true, Desc: "The exact text to find, copied from a wanctl_read of this file. Must be non-empty, and must match exactly once unless `all` is true."},
			{Name: "new", Type: TypeString, CLI: "--new STR | --new-file F", Required: true, Desc: "The text to put in its place. May be an empty string, which deletes `old`."},
			{Name: "old-file", CLI: "--old-file F", Type: TypeString, CLIOnly: true, Desc: "Read the text to find from this local file instead of --old. This is how a multi-line block gets through without fighting the shell over quoting. Giving both --old and --old-file is an error, not a precedence rule."},
			{Name: "new-file", CLI: "--new-file F", Type: TypeString, CLIOnly: true, Desc: "Read the replacement from this local file instead of --new."},
			{Name: "all", Type: TypeBool, CLI: "--all", Desc: "Replace every occurrence instead of refusing when `old` appears more than once. Default false."},
			{Name: "expected_sha256", Type: TypeString, CLI: "--sha SHA256", Desc: "The sha256 wanctl_read reported for this file. When set, the edit is refused if the file no longer hashes to it, so a concurrent change cannot be overwritten silently. Strongly recommended."},
		},
		CLIExample: "wanctl edit --target lab /app.conf --old \"port = 80\" --new \"port = 8080\"\n  wanctl edit --target lab /app.conf --old X --new Y --sha <from read>",
		MCPExample: "wanctl_edit{\"target\":\"lab\",\"path\":\"/app.conf\",\"old\":\"80\",\"new\":\"8080\"}",
		Errors: []Failure{
			{Text: "old string not found", Means: "The `old` text does not appear, usually a whitespace or indentation difference. Re-read the file instead of guessing."},
			{Text: "old string occurs N times", Means: "Add surrounding context so it matches once, or pass --all / all=true if every occurrence is meant."},
			{Text: "changed since it was read", Means: "Someone else wrote to the file. The message carries the current sha256; re-read and redo the edit."},
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "does not support read/edit; run `wanctl update`", Means: "The device is running a wanctl older than the file tools. Update it there, then retry."},
		},
		Handler: "mcpEdit",
	},
	{
		MCPName: "wanctl_exec_async",
		Group:   GroupControl,
		Summary: "Start a background job and return its id at once",
		Desc:    "Start a shell command as a BACKGROUND job on the device and return a job_id IMMEDIATELY, without waiting for it to finish. Use this for anything that may run longer than a single tool call comfortably tolerates — package installs, builds, large downloads, `wsl --shutdown` then a long build, etc. The command keeps running on the device even after this call returns; fetch its output and exit code later with wanctl_exec_poll(job_id). Always runs in a FRESH shell (no shared cwd/env with wanctl_exec's persistent session). Same pairing/policy rules as wanctl_exec. Jobs run for at most 30 minutes, retain at most 8 MiB output each, and finished results remain pollable for up to 1h subject to device-wide retention budgets.",
		Params: []Param{
			{Name: "target", Type: TypeString, Required: true, MCPOnly: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "command", Type: TypeString, Required: true, MCPOnly: true, Desc: "Shell command to run in the device's default shell (sh on Unix, powershell on Windows)."},
			{Name: "cwd", Type: TypeString, MCPOnly: true, Desc: "Working directory on the device for this command (also the policy scope)."},
		},
		MCPExample: "wanctl_exec_async{\"target\":\"lab\",\"command\":\"npm run dev\",\"cwd\":\"/srv\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpExecAsync",
	},
	{
		MCPName: "wanctl_exec_poll",
		Group:   GroupControl,
		Summary: "Fetch a background job's new output and status",
		Desc:    "Fetch a background job's new output and status (started via wanctl_exec_async). Call repeatedly until state is 'done'. Pass the 'next_offset' from the previous poll as 'offset' to receive only NEW output each time; omit or 0 to get everything from the start. The response carries a status header (state: running|done, exit code when done, next_offset) followed by the output.",
		Params: []Param{
			{Name: "target", Type: TypeString, Required: true, MCPOnly: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS — the same device the job was started on."},
			{Name: "job_id", Type: TypeString, Required: true, MCPOnly: true, Desc: "The job id returned by wanctl_exec_async."},
			{Name: "offset", Type: TypeNumber, MCPOnly: true, Desc: "Bytes of output already seen; return only output past this point. Use the previous poll's next_offset. Default 0 = from the start."},
		},
		MCPExample: "wanctl_exec_poll{\"target\":\"home-pc\",\"job_id\":\"j-7f2\",\"offset\":4096}",
		Handler:    "mcpExecPoll",
	},
	{
		Name:      "push",
		MCPName:   "wanctl_push",
		Group:     GroupFiles,
		IndexLine: "copy a local file to a device",
		Summary:   "Upload a local file to a path on the device",
		Desc:      "Upload a local file to a remote path on the target device. Same pairing/policy rules as wanctl_exec. Available in stdio mode only (on a shared HTTP MCP server 'local' would be a path on the server itself). Paths under a dot-directory of the operator's home (~/.ssh, ~/.config, …) are refused; WANCTL_MCP_LOCAL_ROOT confines the tool to one tree. To change part of a file that is already on the device, use wanctl_edit rather than uploading a rewritten copy.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "local", Type: TypeString, CLI: "<local>", Required: true, Desc: "Absolute path on the MCP-server machine (or your local machine in stdio mode) to upload."},
			{Name: "remote", Type: TypeString, CLI: "<remote>", Required: true, Desc: "Absolute path on the target device to write to."},
		},
		CLIExample: "wanctl push --target home-pc ./build/app /opt/app/app",
		MCPExample: "wanctl_push{\"target\":\"lab\",\"local\":\"/tmp/app\",\"remote\":\"/opt/app\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpPush",
	},
	{
		MCPName: "wanctl_push_blob",
		Group:   GroupFiles,
		Summary: "Upload inline base64 content to a path on the device",
		Desc:    "Upload INLINE base64 content to a remote path on the target device — the file-push tool that works in HTTP (remote) MCP mode, where the AI host has no file on the MCP server for wanctl_push to read. Encode the bytes you want written as base64 and pass them in 'content_b64'. Same pairing/policy rules as wanctl_exec. Size cap: 8 MiB of raw (decoded) bytes; for larger payloads, split or have the device fetch the file itself. This tool OVERWRITES the whole file, discarding anything changed since you last read it — to patch an existing file, use wanctl_edit instead.",
		Params: []Param{
			{Name: "target", Type: TypeString, Required: true, MCPOnly: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "remote", Type: TypeString, Required: true, MCPOnly: true, Desc: "Absolute path on the target device to write to (overwrites if it exists)."},
			{Name: "content_b64", Type: TypeString, Required: true, MCPOnly: true, Desc: "Standard-base64-encoded file content (the RAW bytes to write, not text)."},
			{Name: "mode", Type: TypeString, MCPOnly: true, Desc: "Optional octal file mode, e.g. \"0755\" for an executable. Default 0644."},
		},
		MCPExample: "wanctl_push_blob{\"target\":\"lab\",\"remote\":\"/opt/run.sh\",\n                   \"content_b64\":\"\u2026\",\"mode\":\"0755\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
		},
		Handler: "mcpPushBlob",
	},
	{
		Name:      "pull",
		MCPName:   "wanctl_pull",
		Group:     GroupFiles,
		IndexLine: "copy a file from a device to this machine",
		Summary:   "Download a file from the device to a local path",
		Desc:      "Download a remote file from the target device to a local path. Same pairing/policy rules as wanctl_exec. Available in stdio mode only; the same local-path limits as wanctl_push apply. To inspect a text file rather than keep a copy of it — including on a shared HTTP MCP server, where this tool is unavailable — use wanctl_read.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "remote", Type: TypeString, CLI: "<remote>", Required: true, Desc: "Absolute path on the target device to read."},
			{Name: "local", Type: TypeString, CLI: "<local>", Required: true, Desc: "Absolute path on the MCP-server machine (or your local machine in stdio mode) to write to."},
		},
		CLIExample: "wanctl pull --target home-pc /var/log/app.log ./app.log",
		MCPExample: "wanctl_pull{\"target\":\"lab\",\"remote\":\"/var/log/app.log\",\"local\":\"./app\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpPull",
	},
	{
		Name:      "logs",
		MCPName:   "wanctl_logs",
		Group:     GroupControl,
		IndexLine: "read a device's activity log, or portal/relay server logs",
		Summary:   "Read a device's activity log: connects, execs, file operations",
		Desc:      "Pull JSONL activity events from the target device's local log (every connect/exec/file with its decision and exit code). Useful for auditing what happened, including past pairing/approval outcomes.",
		CLINote:   "With no --target this reads THIS machine's own log, which is how a device owner sees what controllers did to it. `wanctl logs --service portal|relay` reads server logs instead; --follow is not supported.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "type", Type: TypeString, CLI: "--type T", Desc: "Filter: 'connect', 'exec', or 'file'."},
			{Name: "grep", Type: TypeString, CLI: "--grep STR", Desc: "Filter: substring of the detail field."},
			{Name: "since", Type: TypeString, CLI: "--since RFC3339", Desc: "Filter: RFC3339 timestamp lower bound."},
			{Name: "limit", Type: TypeNumber, CLI: "--limit N", Desc: "Return at most this many of the most recent matching events (0 = no cap)."},
			{Name: "service", CLI: "--service portal|relay", Type: TypeString, CLIOnly: true, Desc: "Read a SERVER's process log instead of a device's activity log. Needs WANCTL_ADMIN_SECRET; the MCP spelling is the separate tool wanctl_server_logs."},
			{Name: "follow", CLI: "--follow", Type: TypeBool, CLIOnly: true, Desc: "Not yet supported. Named here so that asking for it fails loudly instead of silently printing a snapshot."},
		},
		CLIExample: "wanctl logs --target lab --type exec --since 2026-09-17T00:00:00Z",
		MCPExample: "wanctl_logs{\"target\":\"home-pc\",\"type\":\"exec\",\"limit\":50}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
		},
		Handler: "mcpLogs",
	},
	{
		Name:    "logs --service",
		MCPName: "wanctl_server_logs",
		Summary: "Read recent portal or relay process logs",
		Desc:    "Read recent portal or relay process logs through the secret-gated admin API. Output is redacted before filtering and bounded by the requested limit.",
		Params: []Param{
			{Name: "service", Type: TypeString, CLI: "--service portal|relay", Required: true, Desc: "Server service: 'portal' or 'relay'."},
			{Name: "since", Type: TypeString, CLI: "--since 15m", Desc: "Lookback duration such as '30m' or '2h'. Default 15m."},
			{Name: "limit", Type: TypeNumber, CLI: "--limit N", Desc: "Return at most this many recent lines. Default 200, maximum 2000."},
			{Name: "grep", Type: TypeString, CLI: "--grep STR", Desc: "Filter by substring after credential redaction."},
		},
		CLIExample: "wanctl logs --service relay --since 30m --grep pairing",
		MCPExample: "wanctl_server_logs{\"service\":\"relay\",\"since\":\"30m\"}",
		Errors: []Failure{
			{Text: "WANCTL_ADMIN_SECRET", Means: "The admin API is secret-gated; without the secret in the environment the call is refused."},
		},
		Handler: "mcpServerLogs",
	},
	{
		Name:       "id",
		MCPName:    "wanctl_id",
		Group:      GroupSession,
		IndexLine:  "show this controller's identity fingerprint",
		Summary:    "Show this controller identity's fingerprint",
		Desc:       "Show THIS MCP session's controller identity fingerprint. The fingerprint is what target devices pair against in the trust step.",
		CLIExample: "wanctl id",
		MCPExample: "wanctl_id{}",
		Handler:    "mcpID",
	},
	{
		Name:      "trust",
		MCPName:   "wanctl_trust",
		Group:     GroupSession,
		IndexLine: "list pinned device identities, or trusted controllers",
		Summary:   "List the trust store",
		Desc:      "List the trust store for THIS MCP session. 'servers' (default) = explicitly pinned devices. 'clients' = controllers this machine has trusted to drive it (only meaningful in stdio mode if this machine is also running wanctl agent).",
		Params: []Param{
			{Name: "which", Type: TypeString, CLI: "[clients|servers]", Desc: "'servers' (default) or 'clients'."},
		},
		CLIExample: "wanctl trust servers",
		MCPExample: "wanctl_trust{\"which\":\"servers\"}",
		Handler:    "mcpTrust",
	},
	{
		Name:    "trust server",
		MCPName: "wanctl_trust_server",
		Summary: "Pin a device's identity for this controller",
		Desc:    "Pin a device's identity for THIS session. Call it as soon as any tool returns DEVICE IDENTITY CONFIRMATION REQUIRED, passing the target and fingerprint copied VERBATIM from that result, then retry the call that failed — do not ask the user to confirm the fingerprint first, because your MCP client's own approval prompt is already the human checkpoint. This is a first-contact step only: it records what the device presented right now, so later calls can detect a change. If a call instead returns 'DEVICE IDENTITY MISMATCH', do NOT call this tool — report both the pinned and the presented fingerprint to the user and stop; re-pinning is a human's decision at a terminal. Note: the handler refuses unless the operator has set WANCTL_MCP_ALLOW_UNSAFE_TRUST_SERVER=1 (the hosted endpoint does; a local stdio server usually does not, and there a human runs `wanctl trust server` instead).",
		CLINote: "--replace overwrites an existing pin. That is the deliberate human step after a DEVICE IDENTITY MISMATCH has been investigated and explained; without it, re-pinning a known device is refused.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "The owner/device target, copied verbatim from the DEVICE IDENTITY CONFIRMATION REQUIRED result."},
			{Name: "fingerprint", Type: TypeString, CLI: "--fingerprint SHA256:...", Required: true, Desc: "The SHA256:... fingerprint, copied verbatim from the same result."},
			{Name: "replace", CLI: "--replace", Type: TypeBool, CLIOnly: true, Desc: "Overwrite an existing pin. Without it, re-pinning a known device is refused — that refusal is the whole point of a pin, so passing this is a deliberate human act after a mismatch has been explained."},
		},
		CLIExample: "wanctl trust server --target ns/home-pc --fingerprint SHA256:\u2026 [--replace]",
		MCPExample: "wanctl_trust_server{\"target\":\"ns/home-pc\",\"fingerprint\":\"SHA256:\u2026\"}",
		Errors: []Failure{
			{Text: "DEVICE IDENTITY MISMATCH", Means: "The device presented a different identity than the pinned one. Refused; nothing was sent. Report both fingerprints and stop \u2014 re-pinning is a human decision at a terminal."},
		},
		Handler: "mcpTrustServer",
	},
	{
		Name:      "rules",
		MCPName:   "wanctl_rules",
		Group:     GroupSession,
		IndexLine: "show or change this machine's local policy rules",
		Summary:   "List the policy rules this machine enforces on controllers",
		Desc:      "List the local policy rules (allow-list) on THIS machine. Only meaningful in stdio mode if this machine is also running wanctl agent; for controller-only and HTTP-mode hosts the list is empty.",
		CLINote:   "The CLI also writes: `wanctl rules add` appends a rule and `wanctl rules rm` removes one. Rules are enforced by the agent on THIS machine, so they only mean anything where a device runs.",
		Params: []Param{
			{Name: "kind", CLI: "--kind exec|read|write|logs", Type: TypeString, CLIOnly: true, Desc: "What the rule governs. `wanctl rules add` only."},
			{Name: "pattern", CLI: "--pattern P", Type: TypeString, CLIOnly: true, Desc: "For exec, a command prefix with an optional trailing *. For file kinds, a directory. `wanctl rules add` only."},
			{Name: "dir", CLI: "--dir D", Type: TypeString, CLIOnly: true, Desc: "For an exec rule scoped to a working directory. `wanctl rules add` only."},
		},
		CLIExample: "wanctl rules\n  wanctl rules add --kind exec --pattern \"git *\"",
		MCPExample: "wanctl_rules{}",
		Handler:    "mcpRules",
	},
	{
		Name:       "start",
		IndexRank:  1,
		Group:      GroupDevice,
		IndexLine:  "log in if needed, then run the agent in the background",
		Summary:    "Turn this machine into a controlled device",
		Desc:       "Log in if there is no credential yet, then run the agent detached in the background. This is the command that makes a machine a controlled device: until it runs, nothing can dial in.\n\nPersistence: `wanctl start` survives THIS terminal but may not survive logout or reboot. `wanctl service install` adds OS-native autostart; Linux additionally needs user lingering to come up without a login, and Windows starts the limited-user task at the next logon.",
		CLIExample: "wanctl start",
		Errors: []Failure{
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
	},
	{
		Name:       "stop",
		IndexRank:  2,
		Group:      GroupDevice,
		IndexLine:  "stop the background agent",
		Summary:    "Stop the agent started by `wanctl start`",
		Desc:       "Signal the background agent to shut down and wait for it to release the config-dir lock. An agent that is mid-command finishes it first.",
		CLIExample: "wanctl stop",
	},
	{
		Name:      "service",
		IndexRank: 4,
		Group:     GroupDevice,
		IndexLine: "install/uninstall/status an OS-native always-on service",
		Summary:   "Install, remove or inspect an OS-native always-on service",
		Desc:      "Install the agent as a systemd user unit, a launchd agent or a Windows Scheduled Task, so it comes back without anyone logging in and typing `wanctl start`.\n\n--name and --portal-fps are baked into the unit, because a unit restarts unattended and cannot be asked. Omit --mode so the persisted mode and portal switches survive a restart instead of being frozen at install time.",
		Params: []Param{
			{Name: "name", CLI: "--name N", Type: TypeString, CLIOnly: true, Desc: "Device name baked into the unit."},
			{Name: "portal-fps", CLI: "--portal-fps FP[,FP]", Type: TypeString, CLIOnly: true, Desc: "Portal fingerprints the agent will accept, baked into the unit."},
			{Name: "mode", CLI: "--mode M", Type: TypeString, CLIOnly: true, Desc: "Freeze the policy mode in the unit. Omit it so the persisted mode survives a restart."},
			{Name: "relay", CLI: "--relay URL", Type: TypeString, CLIOnly: true, Desc: "Relay URL baked into the unit. Defaults to the currently configured relay."},
			{Name: "transport", CLI: "--transport ws|http", Type: TypeString, CLIOnly: true, Desc: "Transport baked into the unit. Defaults to the currently configured transport."},
		},
		CLIExample: "wanctl service install --name lab-box\n  wanctl service status\n  wanctl service uninstall",
	},
	{
		Name:      "agent",
		IndexRank: 5,
		Group:     GroupDevice,
		IndexLine: "run the agent in the foreground",
		Summary:   "Run the agent in the foreground",
		Desc:      "Run the device-side agent attached to this terminal — what `wanctl start` and the OS service spawn. Use it to watch policy decisions land in real time, or under your own supervisor.",
		Params: []Param{
			{Name: "name", CLI: "--name N", Type: TypeString, CLIOnly: true, Desc: "Display name for this device. Defaults to the hostname; it does not change the device ID."},
			{Name: "relay", CLI: "--relay URL", Type: TypeString, CLIOnly: true, Desc: "Relay URL. Defaults to the configured one."},
			{Name: "token", CLI: "--token T", Type: TypeString, CLIOnly: true, Desc: "Access or registration token. Defaults to WANCTL_TOKEN, then the stored token."},
			{Name: "transport", CLI: "--transport ws|http", Type: TypeString, CLIOnly: true, Desc: "Transport to the relay. http is proxy-agnostic and works through ordinary reverse proxies."},
			{Name: "mode", CLI: "--mode normal|bypass", Type: TypeString, CLIOnly: true, Desc: "Policy mode. normal prompts on a rule miss; bypass auto-allows and is DANGEROUS. Empty keeps the last persisted mode."},
			{Name: "shell", CLI: "--shell S", Type: TypeString, CLIOnly: true, Desc: "Shell for exec. Defaults to powershell on Windows and /bin/sh elsewhere."},
			{Name: "yes", CLI: "--yes", Type: TypeBool, CLIOnly: true, Desc: "Auto-trust new controllers. For unattended devices only: it removes the human approval step."},
			{Name: "portal-fps", CLI: "--portal-fps FP[,FP]", Type: TypeString, CLIOnly: true, Desc: "Comma-separated portal admin fingerprints to seed locally, so this device accepts that portal's approvals."},
			{Name: "managed", CLI: "--managed", Type: TypeBool, CLIOnly: true, Desc: "The agent is owned by an external supervisor, so it does not try to restart itself."},
		},
		CLIExample: "wanctl agent --name lab-box --relay https://relay.example.com",
	},
	{
		Name:    "update",
		Summary: "Replace this binary with the latest signed release",
		Desc:    "Fetch the release manifest, verify the signature and swap this binary in place. A running agent keeps its pid across the swap, so systemd, launchd and `wanctl status` still point at it. Development builds are never replaced.\n\nOn Android the APK cannot be installed by the binary, so --fetch-apk downloads and verifies it and prints the path for the app to install.",
		Params: []Param{
			{Name: "fetch-apk", CLI: "--fetch-apk DIR", Type: TypeString, CLIOnly: true, Desc: "Android only. Download and verify the APK into this directory, print its path and exit. The binary cannot install an APK; the app does that with the printed path."},
			{Name: "no-restart", CLI: "--no-restart", Type: TypeBool, CLIOnly: true, Desc: "Internal. Skips the daemon stop/start, used by the sudo-elevated second phase of an update."},
		},
		CLIExample: "wanctl update\n  wanctl update --fetch-apk /sdcard/Download",
	},
	{
		Name:       "version",
		Summary:    "Print the release version",
		Desc:       "Print the immutable release version baked into this binary, or `dev` for a local build.",
		CLIExample: "wanctl version",
	},
	{
		Name:    "mcp",
		Summary: "Run wanctl as an MCP server",
		Desc:    "Serve the tools in this contract over the Model Context Protocol.\n\nWith no flags it speaks stdio: one process per AI host, single user, backed by this machine's wanctl config. With --http it serves Streamable HTTP for many users at once, deriving a separate controller identity per namespace from WANCTL_MCP_SEED; wanctl_push and wanctl_pull are withdrawn there, because `local` would name a path on the server rather than on the caller's machine.",
		Params: []Param{
			{Name: "http", CLI: "--http ADDR", Type: TypeString, CLIOnly: true, Desc: "Serve Streamable HTTP on this address (e.g. :8081) instead of stdio. Multi-user: each session derives its own controller identity from WANCTL_MCP_SEED, and wanctl_push/wanctl_pull are withdrawn because 'local' would name a path on the server."},
		},
		CLIExample: "wanctl mcp\n  wanctl mcp --http :8081",
	},
	{
		Name:    "docs",
		Summary: "Read and write the portal's documentation articles",
		Desc:    "List, read, create, edit and remove the articles the portal serves, and the groups they sit in. Bodies come from --file, from $EDITOR with --editor, or from stdin.",
		Params: []Param{
			{Name: "slug", CLI: "--slug S", Type: TypeString, CLIOnly: true, Desc: "URL slug, unique across articles."},
			{Name: "title", CLI: "--title T", Type: TypeString, CLIOnly: true, Desc: "Human title."},
			{Name: "group", CLI: "--group G", Type: TypeString, CLIOnly: true, Desc: "Group slug: a filter for `docs ls`, the destination for `docs new` and `docs edit`."},
			{Name: "position", CLI: "--position N", Type: TypeString, CLIOnly: true, Desc: "Sort order within the group."},
			{Name: "file", CLI: "--file F", Type: TypeString, CLIOnly: true, Desc: "Read the body from this local file. Without it, and without --editor, the body is read from stdin."},
			{Name: "editor", CLI: "--editor", Type: TypeBool, CLIOnly: true, Desc: "Open $EDITOR to write the body."},
		},
		CLIExample: "wanctl docs ls --group quickstart\n  wanctl docs get enroll-device\n  wanctl docs edit enroll-device --file ./enroll.md",
	},
	{
		Name:       "friends",
		Summary:    "List and manage friend relationships between namespaces",
		Desc:       "Sharing a device is only possible between namespaces that have agreed to it, so a friendship is the prerequisite for `wanctl share`. This lists relationships and pending requests, and sends, accepts, declines or removes them.",
		CLIExample: "wanctl friends\n  wanctl friends add other-ns\n  wanctl friends accept other-ns",
	},
	{
		Name:    "share",
		Summary: "Grant another namespace the use of one of your devices",
		Desc:    "Sharing hands a friend the use of a device, not ownership of it: they drive it under your device's policy, and --manage additionally lets them change that policy. Revoking takes effect on their next call.",
		Params: []Param{
			{Name: "device", CLI: "--device DEV", Type: TypeString, CLIOnly: true, Desc: "The device of yours being shared."},
			{Name: "to", CLI: "--to NS", Type: TypeString, CLIOnly: true, Desc: "The friend namespace receiving it. They must already be a friend."},
			{Name: "manage", CLI: "--manage", Type: TypeBool, CLIOnly: true, Desc: "Also let them administer the device \u2014 approvals, rules and mode \u2014 not just use it."},
		},
		CLIExample: "wanctl share grant --device home-pc --to other-ns\n  wanctl share manage --device home-pc --to other-ns on\n  wanctl share revoke --device home-pc --to other-ns",
	},
	{
		Name:      "screenshot",
		Group:     GroupControl,
		IndexLine: "capture an Android screen to a local PNG",
		Summary:   "Capture an Android device's screen to a local PNG",
		Desc:      "`screencap -p` writes a PNG to stdout, and through a shell pipeline stdout is a terminal — a screenful of binary. This writes a file instead, and only writes to stdout when explicitly asked with `-o -`. Implies --elevate, because screencap needs it.",
		Params: []Param{
			{Name: "target", CLI: "[DEVICE] | --target NS/DEV", Type: TypeString, CLIOnly: true, Desc: "Device ID or unique name. It may also be the first positional argument."},
			{Name: "o", CLI: "-o FILE", Type: TypeString, CLIOnly: true, Desc: "Local file to write. Defaults to screenshot-<device>-<time>.png; \"-\" writes the PNG to stdout instead, which is the only way to pipe it."},
			{Name: "via", CLI: "--via su|adb", Type: TypeString, CLIOnly: true, Desc: "Pin the elevation channel: 'su' (rooted device) or 'adb' (the device's own wireless debugging). Default empty lets the device pick."},
		},
		CLIExample: "wanctl screenshot home-phone -o ./screen.png",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
		},
	},
	{
		Name:       "config",
		Summary:    "Show or persist relay, portal and transport settings",
		Desc:       "Show the effective settings and where each came from — a flag, an environment variable, the config file or a value baked into the build — then persist or remove the file-backed ones.",
		CLIExample: "wanctl config\n  wanctl config set relay=https://relay.example.com\n  wanctl config unset portal",
	},
	{
		Name:       "label",
		Summary:    "Show or set this controller's self-description",
		Desc:       "A device refuses to raise a pairing request from a controller that has not said who it is, because the approval screen would otherwise ask a human to trust an anonymous fingerprint.",
		CLIExample: "wanctl label \"Lin's laptop, Claude Code\"",
	},
	{
		Name:    "admin",
		Summary: "Mint, list and revoke admission invites",
		Desc:    "Instance administration for an invite-only relay. Needs WANCTL_ADMIN_SECRET; --github pre-approves a GitHub login instead of minting a code to hand out.",
		Params: []Param{
			{Name: "github", CLI: "--github LOGIN", Type: TypeString, CLIOnly: true, Desc: "Pre-approve this GitHub login instead of minting a code to hand out."},
		},
		CLIExample: "wanctl admin invite --github octocat\n  wanctl admin invites\n  wanctl admin invite-revoke INVITE-ID",
	},
	{
		Name:    "portal-admins",
		Summary: "Manage the local portal root fingerprints",
		Desc:    "The fingerprints this machine accepts as the portal's own identity. Adding one is what lets a self-hosted portal approve pairings for this device.",
		Params: []Param{
			{Name: "fingerprints", CLI: "--fingerprints FP[,FP]", Type: TypeString, CLIOnly: true, Desc: "Comma-separated SHA256 fingerprints to add or remove."},
		},
		CLIExample: "wanctl portal-admins list\n  wanctl portal-admins add SHA256:…",
	},
	{
		Name:    "relay",
		Summary: "Run the relay (the public broker)",
		Desc:    "Run the server side that brokers byte pipes between controllers and devices. It authenticates tokens and authorizes connections but cannot decrypt a session: controllers and devices speak mutual TLS through the pipe, so the relay sees ciphertext. Needs DATABASE_URL or WANCTL_TOKENS.",
		Params: []Param{
			{Name: "addr", CLI: "--addr :PORT", Type: TypeString, CLIOnly: true, Desc: "Listen address. Default :8080."},
		},
		CLIExample: "wanctl relay --addr :8080",
	},
	{
		Name:    "portal",
		Summary: "Run the web portal",
		Desc:    "Run the web front end for login, enrollment, approvals and documentation. It has no database of its own; it authenticates users and scopes calls to the relay's admin API. Logs in with GitHub OAuth, or behind a trusted SSO reverse proxy.",
		Params: []Param{
			{Name: "addr", CLI: "--addr :PORT", Type: TypeString, CLIOnly: true, Desc: "Listen address. Default :8080."},
		},
		CLIExample: "wanctl portal --addr :8080",
	},
	{
		Name:       "help",
		Summary:    "Print this contract",
		Desc:       "With no argument, print the command index. With a command name — either spelling, `read` or `wanctl_read` — print that command's full entry: summary, description, parameters, an example per surface and the error texts to react to. With --markdown, print the whole catalog, which is what docs/contract.md contains.",
		CLIExample: "wanctl help exec\n  wanctl help wanctl_read\n  wanctl help --markdown > docs/contract.md",
	},
}
