package catalog

// Commands is the catalog. The order is the order MCP tools register in,
// which is also the order the Markdown contract prints; the short CLI index
// regroups them by Group instead.
var Commands = []Command{
	{
		Name:      "login",
		MCPName:   "wanctl_login",
		Group:     GroupSession,
		IndexLine: "log in via the portal and save the token (no daemon)",
		Summary:   "Authenticate to a wanctl namespace through the portal",
		Desc:      "Get this session a credential; every other tool needs one before it can reach a device. Reach for it when a tool comes back 'LOGIN REQUIRED', and not before — a session that already has a credential gains nothing from logging in again.\n\nTWO STEPS. Call with NO argument first: you get back a portal URL and a one-time code prompt, and that URL is for the user, verbatim, because only a human at a browser can complete it. Call again with the `code` they paste back and it becomes a namespace token bound ONLY to this MCP session (in HTTP mode) or to this machine's wanctl config (in stdio mode). Several AI users sharing one MCP server each log in for themselves; no credential is ever shared between sessions.\n\nSAVE THE REBIND CREDENTIAL that a successful login returns. HTTP-MCP sessions live in memory, so a relay restart or a dropped connection makes 'LOGIN REQUIRED' surface mid-task even though the user revoked nothing and is still authorized. That is not a reason to send them back to the portal: call wanctl_login(rebind=\"…\") with the credential you saved and access comes back at once, with no round trip through a browser. Go through the OAuth flow again only when you have no saved rebind credential.",
		Params: []Param{
			{Name: "code", Type: TypeString, CLI: "--code CODE", Desc: "The one-time code the user copied from the portal /enroll page. Omit on the first call."},
			{Name: "rebind", Type: TypeString, CLI: "-", MCPOnly: true, Desc: "A rebind credential returned by an earlier successful login in this conversation. Pass it to restore a lost session instantly without re-doing OAuth. Mutually exclusive with code."},
		},
		CLIExample: "wanctl login [--code CODE]",
		MCPExample: "wanctl_login{}  then  wanctl_login{\"code\":\"ABC123\"}",
		Errors: []Failure{
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpLogin",
	},
	{
		Name:      "status",
		IndexRank: 3,
		MCPName:   "wanctl_status",
		Group:     GroupDevice,
		IndexLine: "local agent and credential state, or a remote device's",
		Summary:   "Report login state, and on a device the agent's mode and version",
		Desc:      "Answer \"am I logged in, and as what\" without touching the network. Reach for it when a tool said login was required and you are not sure whether a login already went through, or before telling the user which namespace you are about to act in. It reports the login state, the namespace this session is bound to, and this controller's fingerprint.\n\nIt is not a reachability test. Whether a device exists and can be driven by this token is wanctl_peers; whether a particular device answers right now is the CLI's --target form. A clean status here and a failing exec are not a contradiction.",
		CLINote:   "Without --target this reads local state only and dials nothing. With one it asks that device for its agent mode and version, which is the quickest check that a device is reachable at all.",
		Params: []Param{
			{Name: "target", CLI: "--target NS/DEV", Type: TypeString, CLIOnly: true, Desc: "Ask this device for its agent mode and version instead of reporting local state. Omit it to read this machine only, which dials nothing."},
		},
		CLIExample: "wanctl status [--target NS/DEV]",
		MCPExample: "wanctl_status{}",
		Handler:    "mcpStatus",
	},
	{
		Name:       "logout",
		MCPName:    "wanctl_logout",
		Group:      GroupSession,
		IndexLine:  "stop the agent and forget the saved login",
		Summary:    "Clear the stored credentials",
		Desc:       "Throw this session's credential away. Do it when the user asks to disconnect, or when the session is being handed to someone else — not as housekeeping at the end of a task, because the next tool call would then have to walk a human back through the portal.\n\nAfterwards every tool that touches a device — peers, exec, read, edit, write, push, pull, logs — answers 'LOGIN REQUIRED' until wanctl_login runs again.",
		CLINote:    "On the CLI this also stops a background agent started by `wanctl start`, because a device that can no longer authenticate should not keep a dead connection open.",
		CLIExample: "wanctl logout",
		MCPExample: "wanctl_logout{}",
		Handler:    "mcpLogout",
	},
	{
		Name:       "peers",
		MCPName:    "wanctl_peers",
		Group:      GroupSession,
		IndexLine:  "list the devices this token can reach",
		Summary:    "List reachable devices and whether their identity is pinned",
		Desc:       "Find out what this token can actually drive, before you name a target. Reach for it first whenever the user says a device name you have not used in this session, or asks what is available: a guessed target costs a round trip and returns an error that reads like a fault when it is only a typo. It is a local lookup and dials nothing, so it stays useful even when everything else is failing.\n\nEach entry is a stable device ID with its display label and whether this session has pinned that device's identity yet ('identity: pinned' / 'identity: unpinned'). Unpinned means first contact is still ahead of you: expect DEVICE IDENTITY CONFIRMATION REQUIRED on the first real call to it and answer that yourself with wanctl_trust_server. Structured content carries the same devices and aliases fields as before, plus an identity map keyed by the canonical namespace/device.\n\nA device the user swears exists but that is missing here is not reachable by this token — it is offline, or in another namespace, or shared to you and since revoked. Say that rather than retrying.",
		CLIExample: "wanctl peers",
		MCPExample: "wanctl_peers{}",
		Errors: []Failure{
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpPeers",
	},
	{
		Name:      "pair",
		MCPName:   "wanctl_pair",
		Group:     GroupSession,
		IndexLine: "check trust, or get the URL the device owner approves",
		Summary:   "Check a device's trust state, or get the URL to pair with it",
		Desc:      "Ask whether a device will take orders from this session before you try to give it one. Worth a call when you are about to start something disruptive on a device this session has not used yet, so the user gets the approval link up front rather than halfway through the work. Routine work does not need it: every other tool raises the same refusals on its own.\n\nThree answers, each with its own next move. '✓ already trusted' means go ahead. 'PAIRING REQUIRED' carries a URL valid for five minutes — relay it to the user VERBATIM, never paraphrased or shortened, wait for them to approve, then retry. 'DEVICE IDENTITY CONFIRMATION REQUIRED' is first contact and is yours to answer rather than the user's: call wanctl_trust_server with the target and fingerprint from that result, then call this again. Do not ask permission for that step; your MCP client's own approval prompt is the human checkpoint.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "<device>", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
		},
		CLIExample: "wanctl pair home-pc",
		MCPExample: "wanctl_pair{\"target\":\"home-pc\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "DEVICE IDENTITY MISMATCH", Means: "The device presented a different identity than the pinned one. Refused; nothing was sent. Report both fingerprints and stop \u2014 re-pinning is a human decision at a terminal."},
		},
		Handler: "mcpPair",
	},
	{
		Name:      "exec",
		MCPName:   "wanctl_exec",
		Group:     GroupControl,
		IndexLine: "run a command or script on a device (persistent shell)",
		Summary:   "Run a command, or a whole script, on a device",
		Desc: "Run a command on a machine you are not running on, and get back its stdout, stderr and exit code. This is the general-purpose primitive: reach for it for things that are genuinely commands — git, a package manager, a service check — and not for looking at or changing files, which have their own tools and are covered below.\n\nPass EITHER 'command' (a one-liner) OR 'script' (multi-line source). Choose 'script' the moment the text carries a $, a quote inside a quote, or more than one statement: a script is transported encoded and is never parsed by the device's shell, so what you wrote is what runs. A one-liner is SOURCE CODE for that shell and is parsed there, which is why a nested `powershell -Command \"...$x...\"` is parsed twice and fails with a misleading error.\n\nIf the device has not approved this controller yet, the result is isError=true with a 'PAIRING REQUIRED' message carrying a URL — surface that URL to the user VERBATIM, do not paraphrase it, and retry once they approve. 'DEVICE IDENTITY CONFIRMATION REQUIRED' is first contact instead: call wanctl_trust_server with the target and fingerprint it gives you and retry, without asking the user." +
			"\n\nDEV LOOP — how these primitives fit together, because most work is a loop and not one call: wanctl_exec keeps a persistent shell per device, so cwd and exported variables survive between calls and you can cd once and stay there. Anything that does not return promptly — a dev server, a build, an install — belongs in wanctl_exec_async, which hands back a job_id immediately; follow it with wanctl_exec_poll until state is done, and the server keeps running on the device meanwhile. To look at a file use wanctl_read and to change one use wanctl_edit, never cat/sed/echo through this tool: the file tools are native on the device, identical on every OS, and nothing you pass is parsed by a shell. Reach for wanctl_push_blob only for binaries or for a large file that does not exist on the device yet — it overwrites whole files and loses concurrent edits. Before working inside a project directory, read its AGENTS.md or CLAUDE.md with wanctl_read if one exists, and follow it." +
			"\n\nLONG OUTPUT: what comes back is capped. Past the cap you get the LAST 48 KiB — the end, where a build's error and a script's result live — behind a line that says how many bytes there were in total and names a file ON THE DEVICE holding the whole thing, kept for an hour. Do not re-run the command with a filter you guessed: grep that file with another wanctl_exec. Read the line rather than assuming the file is there: it also says when the device could not keep the output, and when its copy holds only the first 8 MiB.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices. If exactly one device is online for this token, you may pass empty string."},
			{Name: "command", Type: TypeString, CLI: "<command...>", CLIDesc: "The command to run, given as the trailing arguments. It is SOURCE CODE for the device's shell (sh on Unix, powershell on Windows) and is parsed there, so a nested `powershell -Command \"...$x...\"` is parsed twice and loses its variables to the outer pass; wanctl warns when it sees that shape. Use --script instead of nesting an interpreter.", Desc: "A one-liner for the device's default shell (sh on Unix, powershell on Windows). WARNING: this string is SOURCE CODE for that shell and is parsed there. On Windows that means writing `powershell -Command \"...$x...\"` gets parsed TWICE — the outer shell expands $x to nothing and the inner script fails with a misleading 'term is not recognized'. Use 'script' instead of nesting an interpreter here."},
			{Name: "script", Type: TypeString, CLI: "--script <local-file>", CLIDesc: "Path to a script FILE on this machine. Its contents are sent base64-encoded and run on the device, so quoting and character-set rules do not apply: $, backticks, nested quotes and non-ASCII text all arrive literally. The interpreter comes from the extension (.ps1 → PowerShell, .sh or none → sh) unless --interp says otherwise. This is the CLI spelling of the MCP `script` argument, which carries the source itself rather than a path.", Desc: "Script SOURCE to run on the device (not a file path). Sent encoded, so quoting and character-set rules do not apply: $, backticks, nested quotes and non-ASCII text all arrive literally. Requires 'interp'. Use this for multi-statement work; it is the same single call as 'command'. Scripts over ~9KB must be pushed as a file and run by path instead."},
			{Name: "interp", Type: TypeString, CLI: "--interp powershell|sh", CLIDesc: "Override the interpreter --script would infer from the file extension: powershell | sh.", Desc: "Interpreter for 'script': 'powershell' for Windows devices, 'sh' for Unix/macOS/Android. Required when 'script' is set."},
			{Name: "cwd", Type: TypeString, CLI: "-", MCPOnly: true, Desc: "Working directory on the device for this command (also the policy scope)."},
			{Name: "oneshot", Type: TypeBool, CLI: "--oneshot", Desc: "Run in a fresh shell with no persistent session state. Default false — successive exec calls share cwd/env like a real terminal. Note that aborting a command (Ctrl-C, or losing the connection) RESETS the shared session: the command and everything it started are killed, and the next exec starts in the default directory with a default environment. Use --oneshot for anything you may want to abort, so there is no shared state to lose."},
			{Name: "elevate", Type: TypeBool, CLI: "--elevate", Desc: "Android only. Run with elevated privilege (uid 0 or the adb shell uid 2000) instead of the app sandbox the agent normally lives in. This is what makes `pm`, `am`, `input`, `screencap`, `dumpsys`, `settings`, `wm` and `svc` work at all — without it they fail with permission errors or empty output. Elevated commands need their OWN policy rule on the device; a device in bypass mode still refuses them until a human approves, so expect a 'PAIRING/approval' style rejection the first time."},
			{Name: "via", Type: TypeString, CLI: "--via su|adb", Desc: "Pin the elevation channel: 'su' (rooted device) or 'adb' (device's own wireless debugging). Default empty = let the device pick whichever is available. Naming an unavailable channel fails instead of quietly running unprivileged."},
		},
		CLINote:    "On the command line --target may be omitted when the first argument names a device, or when exactly one device is online. --script takes a path to a local file, not the source itself. Background jobs — the wanctl_exec_async and wanctl_exec_poll pair above — have no CLI spelling yet; from a terminal, background the command on the device instead.",
		CLIExample: "wanctl exec --target home-pc \"uname -a\"\n  wanctl exec --target home-pc --script ./setup.sh",
		MCPExample: "wanctl_exec{\"target\":\"home-pc\",\"command\":\"uname -a\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "DEVICE IDENTITY MISMATCH", Means: "The device presented a different identity than the pinned one. Refused; nothing was sent. Report both fingerprints and stop \u2014 re-pinning is a human decision at a terminal."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpExec",
	},
	{
		Name:      "read",
		MCPName:   "wanctl_read",
		Group:     GroupFiles,
		IndexLine: "print a line range of a text file on a device",
		Summary:   "Read a range of lines from a text file on a device",
		Desc: "Read a range of lines from a text file on a remote wanctl-enrolled device. Use this instead of `wanctl_exec` with cat/head/sed/Get-Content whenever you want to LOOK at a file: it is performed natively on the device, so it behaves identically on Linux, macOS, Windows and Android, nothing is parsed by a shell, and the reply tells you exactly what you got — 'lines A-B of N', the file's size, and the sha256 OF THE WHOLE FILE. Save that sha256: passing it back as wanctl_edit's expected_sha256 is how you make sure you are patching the text you actually read. Reads at most 256 KiB of content per call, and always cuts on a line boundary: when the range is cut short the result says truncated=true and names the `offset` to continue from, so paging never loses or repeats a line. The one exception is a single line bigger than 256 KiB, which cannot be returned whole — the result names that line and tells you to read it with wanctl_exec (sed/cut) instead; do not page on, because the same line would come back every time. Errors: 'not a UTF-8 text file' means the file is binary — use wanctl_pull or wanctl_exec instead, do not retry. Same pairing/policy rules as wanctl_exec: 'PAIRING REQUIRED' carries a URL to relay VERBATIM to the user, 'DEVICE IDENTITY CONFIRMATION REQUIRED' means call wanctl_trust_server and retry, and 'read denied by device policy' means the device's owner has not granted read access to that path." +
			"\n\nBefore working inside a project directory, read its AGENTS.md or CLAUDE.md with wanctl_read if one exists, and follow it: those are the project's own instructions and they outrank how you would otherwise proceed.",
		CLINote: "The content goes to stdout and the trailer — line numbers, the whole file's sha256, whether the 256 KiB cap cut the range short — goes to stderr, so `wanctl read … > file` captures exactly the file content.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
			{Name: "path", Type: TypeString, CLI: "<path>", Required: true, Desc: "Absolute path on the target device. `~` is NOT expanded — spell the home directory out."},
			{Name: "offset", Type: TypeNumber, CLI: "--offset N", Desc: "1-based line number to start at. Default 1. Use this to page through a file that came back truncated."},
			{Name: "limit", Type: TypeNumber, CLI: "--limit N", Desc: "Maximum number of lines to return. Default 2000. The 256 KiB byte cap applies regardless."},
		},
		CLIExample: "wanctl read --target home-pc /etc/hosts --offset 1 --limit 200",
		MCPExample: "wanctl_read{\"target\":\"home-pc\",\"path\":\"/etc/hosts\",\"limit\":200}",
		Errors: []Failure{
			{Text: "not a UTF-8 text file", Means: "The file is binary. Use pull (or exec) instead; retrying read will not help."},
			{Text: "read denied by device policy", Means: "The device owner has not granted read access to that path."},
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "result unknown: the connection dropped", Means: "The request reached the device; the answer did not come back. A read changes nothing, so simply retry."},
			{Text: "does not support read/edit; run `wanctl update`", Means: "The device is running a wanctl older than the file tools. Update it there, then retry."},
		},
		Handler: "mcpRead",
	},
	{
		Name:      "edit",
		MCPName:   "wanctl_edit",
		Group:     GroupFiles,
		IndexLine: "replace an exact string inside a file on a device",
		Summary:   "Replace a string inside a file on a device, atomically",
		Desc:      "Replace text inside a file on a remote device, in place. This is the tool for PATCHING a remote file: it is the exact-string edit you are used to locally, performed natively on the device, so no shell parses your text ($, backticks, quotes and newlines all arrive literally) and the rest of the file is preserved byte for byte — CRLF line endings stay CRLF, the file mode is kept, and the write is atomic (temp file + rename), so a reader never sees a half-written file. Use it for CHANGES to an existing file; to create a file or rewrite one end to end use wanctl_write, and prefer either over wanctl_push_blob, which silently discards anything that changed since you last read the file.\n\nWORKFLOW: wanctl_read the file, copy its sha256 into expected_sha256 here, and pass enough surrounding text in `old` that it matches exactly once.\n\nSEVERAL EDITS AT ONCE: pass `edits` — a list of {old, new} — instead of old/new, and make ONE call with several entries rather than several calls. Every entry matches the file as you read it, not the result of the entry before it, so you never have to imagine the intermediate text. Keep each `old` as SMALL as it can be while still matching exactly once: do not pad it with unchanged lines above and below, and do not include regions you are not changing. The whole batch is checked before anything is written — an entry that matches twice, an entry that matches nothing, or two entries claiming the same bytes refuses the call by index and leaves the file exactly as it was. `all` belongs to the single old/new form only; expected_sha256 works with both. At most 64 entries in one call — send a larger patch as several batches.\n\nREFUSALS (the file is left untouched every time — fix the input and retry, do not fall back to exec): 'old string not found' means your `old` does not appear, usually because of whitespace or indentation, so re-read the file rather than guessing; 'old string occurs N times' means you must add surrounding context to disambiguate, or pass all=true if you really do mean every occurrence; 'changed since it was read' means someone else wrote to the file — the message carries the file's CURRENT sha256, so re-read and redo the edit against the new text. Files over 8 MiB are refused. One outcome is neither: 'result unknown: the connection dropped after the request was sent' means the device got the request and the answer was lost, so the edit may already be in the file \u2014 wanctl_read it and compare the sha256 before doing anything else, and never just repeat the call. Policy: an edit is a WRITE on the device and needs the same grant as wanctl_push; a first edit on an unapproved path may wait for the device owner to approve it.",
		CLINote:   "--old-file and --new-file read the text from a local file, which is how a multi-line block gets through without fighting the shell over quoting. Giving both --old and --old-file is an error rather than a precedence rule.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
			{Name: "path", Type: TypeString, CLI: "<path>", Required: true, Desc: "Absolute path on the target device. `~` is NOT expanded."},
			{Name: "old", Type: TypeString, CLI: "--old STR | --old-file F", Desc: "The exact text to find, copied from a wanctl_read of this file. Must be non-empty, and must match exactly once unless `all` is true. Required unless you pass `edits` instead; giving both forms is refused rather than resolved."},
			{Name: "new", Type: TypeString, CLI: "--new STR | --new-file F", Desc: "The text to put in its place. May be an empty string, which deletes `old`. Belongs with `old`, not with `edits`."},
			{Name: "edits", Type: TypeArray, CLI: NotOnCLI, MCPOnly: true,
				Items: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"old": map[string]any{"type": "string", "description": "Exact text to find, unique in the file as you read it."},
						"new": map[string]any{"type": "string", "description": "What to put there; empty deletes it."},
					},
					"required": []string{"old", "new"},
				},
				Desc: "Several replacements applied to this file in one atomic call, as [{\"old\":…,\"new\":…}, …]. Use this instead of repeating the tool: each `old` matches the ORIGINAL text you read, each must occur exactly once, and two entries may not overlap. Keep every `old` as small as it can be while unique — padding with unchanged context is what makes an entry collide with the next one. At most 64 entries. Mutually exclusive with old/new."},
			{Name: "old-file", CLI: "--old-file F", Type: TypeString, CLIOnly: true, Desc: "Read the text to find from this local file instead of --old. This is how a multi-line block gets through without fighting the shell over quoting. Giving both --old and --old-file is an error, not a precedence rule."},
			{Name: "new-file", CLI: "--new-file F", Type: TypeString, CLIOnly: true, Desc: "Read the replacement from this local file instead of --new."},
			{Name: "all", Type: TypeBool, CLI: "--all", Desc: "Replace every occurrence instead of refusing when `old` appears more than once. Default false."},
			{Name: "expected_sha256", Type: TypeString, CLI: "--sha SHA256", Desc: "The sha256 wanctl_read reported for this file. When set, the edit is refused if the file no longer hashes to it, so a concurrent change cannot be overwritten silently. Strongly recommended."},
		},
		CLIExample: "wanctl edit --target lab /app.conf --old \"port = 80\" --new \"port = 8080\"\n  wanctl edit --target lab /app.conf --old X --new Y --sha <from read>",
		MCPExample: "wanctl_edit{\"target\":\"lab\",\"path\":\"/a.conf\",\"old\":\"80\",\"new\":\"8080\"}\n  wanctl_edit{\"target\":\"lab\",\"path\":\"/a.conf\",\"edits\":[\n    {\"old\":\"port = 80\",\"new\":\"port = 8080\"},\n    {\"old\":\"debug = on\",\"new\":\"debug = off\"}]}",
		Errors: []Failure{
			{Text: "old string not found", Means: "The `old` text does not appear, usually a whitespace or indentation difference. Re-read the file instead of guessing."},
			{Text: "old string occurs N times", Means: "Add surrounding context so it matches once, or pass --all / all=true if every occurrence is meant."},
			{Text: "changed since it was read", Means: "Someone else wrote to the file. The message carries the current sha256; re-read and redo the edit."},
			{Text: "edits[N]: old string occurs M times", Means: "That entry of the batch is ambiguous. Nothing was written; give entry N more surrounding text and send the whole batch again."},
			{Text: "edits[N] overlaps edits[M]", Means: "Two entries claim the same bytes. Nothing was written; merge them into one entry."},
			{Text: "over the 64-entry limit", Means: "Too many entries in one call. Nothing was written; split the patch into several batches."},
			{Text: "pass either 'old'/'new' or 'edits', not both", Means: "The call mixed the two forms. Pick one and resend."},
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "result unknown: the connection dropped", Means: "The request reached the device; the answer did not come back. It may or may not have been applied \u2014 read the file and compare its sha256 before retrying, rather than repeating the operation blindly."},
			{Text: "does not support read/edit; run `wanctl update`", Means: "The device is running a wanctl older than the file tools. Update it there, then retry."},
		},
		Handler: "mcpEdit",
	},
	{
		Name:      "write",
		MCPName:   "wanctl_write",
		Group:     GroupFiles,
		IndexLine: "create or replace a whole text file on a device",
		Summary:   "Create or completely replace a text file on a device",
		Desc:      "Create a text file on a remote device, or replace one end to end, with the content you pass inline. Use write only for NEW files or COMPLETE rewrites; for changes to an existing file use wanctl_edit, which leaves the rest of the file untouched and cannot silently drop someone else's change. Missing parent directories are created. An existing file keeps its mode — a 0755 script stays executable — and a new one gets 0644. The write is atomic (temp file + rename), so a reader sees either the old file or the new one. Content is UTF-8 TEXT: 8 MiB at most, and bytes that are not valid UTF-8 are refused, because they would not survive the trip. Binaries go through wanctl_push_blob (MCP) or wanctl push (CLI) instead. If a call comes back 'result unknown: the connection dropped after the request was sent', the device got it and the answer was lost: read the file and compare its sha256 before retrying. Policy: a write is the same grant as wanctl_push and wanctl_edit, so a first write to an unapproved path may wait for the device owner to approve it.",
		CLINote:   "--content takes the text directly and --content-file reads it from a local file, which is how a multi-line file gets through without fighting the shell over quoting. Giving both is an error rather than a precedence rule.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices."},
			{Name: "path", Type: TypeString, CLI: "<path>", Required: true, Desc: "Absolute path on the target device. `~` is NOT expanded. Parent directories are created if they do not exist."},
			{Name: "content", Type: TypeString, CLI: "--content STR | --content-file F", Required: true, Desc: "The whole new text of the file, UTF-8. An empty string is allowed and writes an empty file. Nothing is appended: whatever was there before is gone."},
			{Name: "content-file", CLI: "--content-file F", Type: TypeString, CLIOnly: true, Desc: "Read the content from this local file instead of --content. Giving both is an error, not a precedence rule."},
		},
		CLIExample: "wanctl write --target lab /etc/app/config.toml --content-file ./config.toml",
		MCPExample: "wanctl_write{\"target\":\"lab\",\"path\":\"/srv/run.sh\",\n    \"content\":\"#!/bin/sh\\nexec ./app\\n\"}",
		Errors: []Failure{
			{Text: "not a UTF-8 text file", Means: "The content is not text. Use push_blob (MCP) or push (CLI) for bytes; retrying write will not help."},
			{Text: "over the 8388608-byte write limit", Means: "Too large for an inline write. Upload it with push, or split it."},
			{Text: "write denied by device policy", Means: "The device owner has not granted write access to that path."},
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "result unknown: the connection dropped", Means: "The request reached the device; the answer did not come back. It may or may not have been applied \u2014 read the file and compare its sha256 before retrying, rather than repeating the operation blindly."},
			{Text: "does not support write; run `wanctl update`", Means: "The device is running a wanctl older than the write tool. Update it there, then retry."},
		},
		Handler: "mcpWrite",
	},
	{
		MCPName: "wanctl_exec_async",
		Group:   GroupControl,
		Summary: "Start a background job and return its id at once",
		Desc:    "Start work that will not finish inside one tool call, and get a job_id back immediately. Reach for it BEFORE starting anything whose length you cannot honestly predict — a package install, a build, a large download, a dev server meant to stay up — because wanctl_exec holds the call open until the command ends, and a call that times out loses both the output and the knowledge that the thing is still running. Here the command keeps running on the device after this returns; collect its output and exit code with wanctl_exec_poll(job_id).\n\nIt always runs in a FRESH shell. It does not inherit the working directory or the exported variables of wanctl_exec's persistent session, so pass 'cwd' explicitly instead of relying on a cd from an earlier call. Pairing, device identity and policy are exactly as for wanctl_exec.\n\nThe ceilings are real: a job runs for at most 30 minutes, keeps at most 8 MiB of output, and stays pollable for up to an hour after it ends, subject to the device's overall retention budget. Anything that has to outlive those belongs in something the device itself supervises — a service, a scheduled task — started through this tool once.",
		Params: []Param{
			{Name: "target", Type: TypeString, Required: true, MCPOnly: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "command", Type: TypeString, Required: true, MCPOnly: true, Desc: "Shell command to run in the device's default shell (sh on Unix, powershell on Windows)."},
			{Name: "cwd", Type: TypeString, MCPOnly: true, Desc: "Working directory on the device for this command (also the policy scope)."},
		},
		MCPExample: "wanctl_exec_async{\"target\":\"lab\",\"command\":\"npm run dev\",\"cwd\":\"/srv\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpExecAsync",
	},
	{
		MCPName: "wanctl_exec_poll",
		Group:   GroupControl,
		Summary: "Fetch a background job's new output and status",
		Desc:    "Collect what a background job has produced since you last looked. Call it after wanctl_exec_async and keep calling until state is 'done', which is also the only point at which an exit code exists — before that a job has no result, only output so far.\n\nPass the previous poll's 'next_offset' back as 'offset' so each call returns only NEW output. Omit it or pass 0 only when you deliberately want everything from the start; re-reading the beginning on every poll is how a long build's output fills a conversation for no gain. The reply opens with a status header — state running|done, the exit code once done, next_offset — and the output follows it.\n\nA poll that returns no new output is neither a failure nor a reason to start the job again: it means nothing has been written since your last call. Wait, do something else, and poll again. Starting a second copy of a build is worse than waiting for the first.",
		Params: []Param{
			{Name: "target", Type: TypeString, Required: true, MCPOnly: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS — the same device the job was started on."},
			{Name: "job_id", Type: TypeString, Required: true, MCPOnly: true, Desc: "The job id returned by wanctl_exec_async."},
			{Name: "offset", Type: TypeNumber, MCPOnly: true, Desc: "Bytes of output already seen; return only output past this point. Use the previous poll's next_offset. Default 0 = from the start."},
		},
		MCPExample: "wanctl_exec_poll{\"target\":\"home-pc\",\"job_id\":\"j-7f2\",\"offset\":4096}",
		Handler:    "mcpExecPoll",
	},
	{
		Name:      "push",
		MCPName:   "wanctl_push",
		Group:     GroupFiles,
		IndexLine: "copy a local file to a device",
		Summary:   "Upload a local file to a path on the device",
		Desc:      "Send a file that already exists on this machine to a path on the device. Reach for it for bytes you cannot type out: a compiled binary, an archive, an image. For anything expressible as text, prefer wanctl_write to create a file and wanctl_edit to change one — this tool replaces a whole file and silently discards whatever changed on the device since you last read it.\n\nAvailable in stdio mode only. On a shared HTTP MCP server it is withdrawn, because 'local' would name a path on the server rather than on the caller's machine; there the equivalent is wanctl_push_blob with inline content.\n\nLocal paths are deliberately fenced: anything under a dot-directory of the operator's home (~/.ssh, ~/.config and the like) is refused, and when WANCTL_MCP_LOCAL_ROOT is set the tool cannot read outside that tree. Those refusals are the operator's policy rather than a transient error — report them and stop, do not go looking for another path to the same bytes. Pairing and device policy are the same as for wanctl_exec.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "local", Type: TypeString, CLI: "<local>", Required: true, Desc: "Absolute path on the MCP-server machine (or your local machine in stdio mode) to upload."},
			{Name: "remote", Type: TypeString, CLI: "<remote>", Required: true, Desc: "Absolute path on the target device to write to."},
		},
		CLIExample: "wanctl push --target home-pc ./build/app /opt/app/app",
		MCPExample: "wanctl_push{\"target\":\"lab\",\"local\":\"/tmp/app\",\"remote\":\"/opt/app\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpPush",
	},
	{
		MCPName: "wanctl_push_blob",
		Group:   GroupFiles,
		Summary: "Upload inline base64 content to a path on the device",
		Desc:    "Put bytes on the device when you have no file on the MCP server to send — the normal case in HTTP (remote) MCP mode, where wanctl_push is withdrawn because the AI host's files are not on the server. Encode what you want written as standard base64 and pass it in 'content_b64'.\n\nReach for it for BINARY content. Text does not belong here: wanctl_write takes the content directly with no encoding step, and a CHANGE to a file that is already on the device belongs in wanctl_edit, because this tool overwrites the file whole and anything edited since you last read it is gone without a word.\n\nThe cap is 8 MiB of raw (decoded) bytes; a larger body is refused, not truncated. Past that, split the payload or have the device fetch the file itself with wanctl_exec. Pairing and device policy are the same as for wanctl_exec.",
		Params: []Param{
			{Name: "target", Type: TypeString, Required: true, MCPOnly: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "remote", Type: TypeString, Required: true, MCPOnly: true, Desc: "Absolute path on the target device to write to (overwrites if it exists)."},
			{Name: "content_b64", Type: TypeString, Required: true, MCPOnly: true, Desc: "Standard-base64-encoded file content (the RAW bytes to write, not text)."},
			{Name: "mode", Type: TypeString, MCPOnly: true, Desc: "Optional octal file mode, e.g. \"0755\" for an executable. Default 0644."},
		},
		MCPExample: "wanctl_push_blob{\"target\":\"lab\",\"remote\":\"/opt/run.sh\",\n                   \"content_b64\":\"\u2026\",\"mode\":\"0755\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
		},
		Handler: "mcpPushBlob",
	},
	{
		Name:      "pull",
		MCPName:   "wanctl_pull",
		Group:     GroupFiles,
		IndexLine: "copy a file from a device to this machine",
		Summary:   "Download a file from the device to a local path",
		Desc:      "Bring a file off the device and keep it on this machine. Reach for it only when you need the actual bytes locally — a binary, an archive, a log you will hand to another tool. To LOOK at a text file, use wanctl_read instead: it needs no local file, it reports line ranges and the whole file's sha256, and it works on a shared HTTP MCP server where this tool is unavailable.\n\nstdio mode only, and the same local-path limits as wanctl_push apply: dot-directories of the operator's home are refused and WANCTL_MCP_LOCAL_ROOT confines the tool to one tree. Pairing and device policy are the same as for wanctl_exec.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "remote", Type: TypeString, CLI: "<remote>", Required: true, Desc: "Absolute path on the target device to read."},
			{Name: "local", Type: TypeString, CLI: "<local>", Required: true, Desc: "Absolute path on the MCP-server machine (or your local machine in stdio mode) to write to."},
		},
		CLIExample: "wanctl pull --target home-pc /var/log/app.log ./app.log",
		MCPExample: "wanctl_pull{\"target\":\"lab\",\"remote\":\"/var/log/app.log\",\"local\":\"./app\"}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
		Handler: "mcpPull",
	},
	{
		Name:      "logs",
		MCPName:   "wanctl_logs",
		Group:     GroupControl,
		IndexLine: "read a device's activity log, or portal/relay server logs",
		Summary:   "Read a device's activity log: connects, execs, file operations",
		Desc:      "Find out what actually happened on a device, as the device itself recorded it. Reach for it when a call was refused and you need to know whether the owner ever saw the request, when the user asks what a controller did to their machine, or when an exec's own output does not explain its outcome. Every connect, exec and file operation is one JSONL event carrying the policy decision and the exit code, which is where an approval that was granted — or quietly never was — becomes visible.\n\nThis is the LOG, not live state. It will not say whether a device is online now (wanctl_peers) or whether a background job is still running (wanctl_exec_poll). Narrow with 'type', 'grep' and 'since' rather than pulling everything and reading it here, and note that 'limit' keeps the most recent matches rather than the first.",
		CLINote:   "With no --target this reads THIS machine's own log, which is how a device owner sees what controllers did to it. `wanctl logs --service portal|relay` reads server logs instead; --follow is not supported.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS."},
			{Name: "type", Type: TypeString, CLI: "--type T", Desc: "Filter: 'connect', 'exec', or 'file'."},
			{Name: "grep", Type: TypeString, CLI: "--grep STR", Desc: "Filter: substring of the detail field."},
			{Name: "since", Type: TypeString, CLI: "--since RFC3339", Desc: "Filter: RFC3339 timestamp lower bound."},
			{Name: "limit", Type: TypeNumber, CLI: "--limit N", Desc: "Return at most this many of the most recent matching events (0 = no cap)."},
			{Name: "service", CLI: "--service portal|relay", Type: TypeString, CLIOnly: true, Desc: "Read a SERVER's process log instead of a device's activity log. Needs WANCTL_ADMIN_SECRET; the MCP spelling is the separate tool wanctl_server_logs."},
			{Name: "follow", CLI: "--follow", Type: TypeBool, CLIOnly: true, Desc: "Not yet supported. Named here so that asking for it fails loudly instead of silently printing a snapshot."},
		},
		CLIExample: "wanctl logs --target lab --type exec --since 2026-09-17T00:00:00Z",
		MCPExample: "wanctl_logs{\"target\":\"home-pc\",\"type\":\"exec\",\"limit\":50}",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
		},
		Handler: "mcpLogs",
	},
	{
		Name:    "logs --service",
		MCPName: "wanctl_server_logs",
		Summary: "Read recent portal or relay process logs",
		Desc:    "Read the portal's or the relay's own process log, for the one question a device's log cannot answer: whether the failure is on the server side at all. Reach for it when calls fail for every device rather than one, or when a pairing a user swears they approved never seems to arrive — not for auditing what a controller did to a device, which is wanctl_logs.\n\nIt is gated on WANCTL_ADMIN_SECRET in the server's environment. Without it the call is refused and retrying changes nothing: say so and move on, because an ordinary user is not meant to have it. Output is redacted before your filter runs, so a 'grep' for a token or a code finds nothing even when the line is there — filter on the surrounding words instead. Keep 'since' short; the default lookback is 15 minutes and the hard cap is 2000 lines.",
		Params: []Param{
			{Name: "service", Type: TypeString, CLI: "--service portal|relay", Required: true, Desc: "Server service: 'portal' or 'relay'."},
			{Name: "since", Type: TypeString, CLI: "--since 15m", Desc: "Lookback duration such as '30m' or '2h'. Default 15m."},
			{Name: "limit", Type: TypeNumber, CLI: "--limit N", Desc: "Return at most this many recent lines. Default 200, maximum 2000."},
			{Name: "grep", Type: TypeString, CLI: "--grep STR", Desc: "Filter by substring after credential redaction."},
		},
		CLIExample: "wanctl logs --service relay --since 30m --grep pairing",
		MCPExample: "wanctl_server_logs{\"service\":\"relay\",\"since\":\"30m\"}",
		Errors: []Failure{
			{Text: "WANCTL_ADMIN_SECRET", Means: "The admin API is secret-gated; without the secret in the environment the call is refused."},
		},
		Handler: "mcpServerLogs",
	},
	{
		Name:       "id",
		MCPName:    "wanctl_id",
		Group:      GroupSession,
		IndexLine:  "show this controller's identity fingerprint",
		Summary:    "Show this controller identity's fingerprint",
		Desc:       "Show THIS controller's own fingerprint — the string a device owner sees on the approval screen and pins. Reach for it when a user is standing at their device deciding whether to approve a pairing and wants to check that the fingerprint in front of them is yours, or when a device lists a trusted controller and the question is whether that is this session.\n\nIt is about this side of the connection only. The DEVICE's fingerprint, the one you pin with wanctl_trust_server, is a different string and never comes from here — it arrives inside the DEVICE IDENTITY CONFIRMATION REQUIRED message.",
		CLIExample: "wanctl id",
		MCPExample: "wanctl_id{}",
		Handler:    "mcpID",
	},
	{
		Name:      "trust",
		MCPName:   "wanctl_trust",
		Group:     GroupSession,
		IndexLine: "list pinned device identities, or trusted controllers",
		Summary:   "List the trust store",
		Desc:      "List what this session has already decided to trust, which is how you tell first contact from a changed identity before acting on either. 'servers' (the default) is the devices whose identity this session has pinned: a target that is missing from that list will raise DEVICE IDENTITY CONFIRMATION REQUIRED on the next call and you answer it with wanctl_trust_server, while a target that IS in the list and raises DEVICE IDENTITY MISMATCH has changed under you and is a matter for the user, not for another tool call.\n\n'clients' is the other direction — controllers this machine has allowed to drive it — and only means anything in stdio mode on a machine that is also running wanctl agent. On a controller-only host, and on an HTTP MCP server, it is empty, and that emptiness is normal rather than a symptom.",
		Params: []Param{
			{Name: "which", Type: TypeString, CLI: "[clients|servers]", Desc: "'servers' (default) or 'clients'."},
		},
		CLIExample: "wanctl trust servers",
		MCPExample: "wanctl_trust{\"which\":\"servers\"}",
		Handler:    "mcpTrust",
	},
	{
		Name:    "trust server",
		MCPName: "wanctl_trust_server",
		Summary: "Pin a device's identity for this controller",
		Desc:    "Pin what a device presented on first contact, so that a later change in its identity can be detected. Call it as soon as any tool returns DEVICE IDENTITY CONFIRMATION REQUIRED, passing the target and fingerprint copied VERBATIM out of that result, then retry the call that failed. Do not stop to ask the user to confirm the fingerprint first: your MCP client's own approval prompt is already the human checkpoint, and on first contact there is nothing to compare the fingerprint against anyway. This records what the device presented right now; that is its whole purpose, and it is a one-time step per device.\n\n'DEVICE IDENTITY MISMATCH' is the opposite situation, and this tool is the wrong answer to it. There the device presented something other than what is pinned — a reinstall, or someone standing in the middle. Do NOT call this tool: report both the pinned and the presented fingerprint to the user and stop. Re-pinning is a decision a human makes at a terminal with `wanctl trust server --replace`.\n\nThe handler refuses outright unless the operator has set WANCTL_MCP_ALLOW_UNSAFE_TRUST_SERVER=1. The hosted endpoint sets it; a local stdio server usually does not, and there the way forward is to tell the user to run `wanctl trust server` themselves rather than to retry.",
		CLINote: "--replace overwrites an existing pin. That is the deliberate human step after a DEVICE IDENTITY MISMATCH has been investigated and explained; without it, re-pinning a known device is refused.",
		Params: []Param{
			{Name: "target", Type: TypeString, CLI: "--target NS/DEV", Required: true, Desc: "The owner/device target, copied verbatim from the DEVICE IDENTITY CONFIRMATION REQUIRED result."},
			{Name: "fingerprint", Type: TypeString, CLI: "--fingerprint SHA256:...", Required: true, Desc: "The SHA256:... fingerprint, copied verbatim from the same result."},
			{Name: "replace", CLI: "--replace", Type: TypeBool, CLIOnly: true, Desc: "Overwrite an existing pin. Without it, re-pinning a known device is refused — that refusal is the whole point of a pin, so passing this is a deliberate human act after a mismatch has been explained."},
		},
		CLIExample: "wanctl trust server --target ns/home-pc --fingerprint SHA256:\u2026 [--replace]",
		MCPExample: "wanctl_trust_server{\"target\":\"ns/home-pc\",\"fingerprint\":\"SHA256:\u2026\"}",
		Errors: []Failure{
			{Text: "DEVICE IDENTITY MISMATCH", Means: "The device presented a different identity than the pinned one. Refused; nothing was sent. Report both fingerprints and stop \u2014 re-pinning is a human decision at a terminal."},
		},
		Handler: "mcpTrustServer",
	},
	{
		Name:      "rules",
		MCPName:   "wanctl_rules",
		Group:     GroupSession,
		IndexLine: "show or change this machine's local policy rules",
		Summary:   "List the policy rules this machine enforces on controllers",
		Desc:      "List the policy THIS machine enforces on controllers that dial into it — what the agent running here allows without stopping to ask a human. Read it when you are working on the device side of the connection and want to know why a controller is being refused.\n\nIt says nothing about what a remote device will let you do. A 'denied by device policy' answer from exec, read, write or screenshot comes from that device's own rules, which live on that device and cannot be read from here; the way through is its owner approving the pending request, not a call to this tool.\n\nOnly meaningful in stdio mode on a machine that is also running wanctl agent. For a controller-only host and for an HTTP MCP server the list is empty, and that is not a fault to investigate.",
		CLINote:   "The CLI also writes: `wanctl rules add` appends a rule and `wanctl rules rm` removes one. Rules are enforced by the agent on THIS machine, so they only mean anything where a device runs.",
		Params: []Param{
			{Name: "kind", CLI: "--kind exec|exec-elevated|read|write|logs", Type: TypeString, CLIOnly: true, Desc: "What the rule governs. `exec-elevated` is its own class: an `exec` rule never authorizes the elevated form of the same command, and on a device where bypass mode is on but the elevation channel is off this is the only way to pre-authorize one. `wanctl rules add` only."},
			{Name: "pattern", CLI: "--pattern P", Type: TypeString, CLIOnly: true, Desc: "For exec and exec-elevated, a command prefix with an optional trailing *; for a command sent with --script, the `script:<interp>:<sha256>` token the device names it by (a refusal prints it in full; approval cards abbreviate it). For file kinds, a directory. `wanctl rules add` only."},
			{Name: "dir", CLI: "--dir D", Type: TypeString, CLIOnly: true, Desc: "For an exec or exec-elevated rule scoped to a working directory. `wanctl rules add` only."},
		},
		CLIExample: "wanctl rules\n  wanctl rules add --kind exec --pattern \"git *\"\n  wanctl rules add --kind exec-elevated --pattern \"pm install *\"",
		MCPExample: "wanctl_rules{}",
		Handler:    "mcpRules",
	},
	{
		Name:       "start",
		IndexRank:  1,
		Group:      GroupDevice,
		IndexLine:  "log in if needed, then run the agent in the background",
		Summary:    "Turn this machine into a controlled device",
		Desc:       "Log in if there is no credential yet, then run the agent detached in the background. This is the command that makes a machine a controlled device: until it runs, nothing can dial in.\n\nPersistence: `wanctl start` survives THIS terminal but may not survive logout or reboot. `wanctl service install` adds OS-native autostart; Linux additionally needs user lingering to come up without a login, and Windows starts the limited-user task at the next logon.",
		CLIExample: "wanctl start",
		Errors: []Failure{
			{Text: "LOGIN REQUIRED", Means: "No usable credential. Run `wanctl login` (CLI) or wanctl_login (MCP); an MCP session that had one can restore it instantly with wanctl_login(rebind=\u2026)."},
		},
	},
	{
		Name:       "stop",
		IndexRank:  2,
		Group:      GroupDevice,
		IndexLine:  "stop the background agent",
		Summary:    "Stop the agent started by `wanctl start`",
		Desc:       "Signal the background agent to shut down and wait for it to release the config-dir lock. An agent that is mid-command finishes it first.",
		CLIExample: "wanctl stop",
	},
	{
		Name:      "service",
		IndexRank: 4,
		Group:     GroupDevice,
		IndexLine: "install/uninstall/status an OS-native always-on service",
		Summary:   "Install, remove or inspect an OS-native always-on service",
		Desc:      "Install the agent as a systemd user unit, a launchd agent or a Windows Scheduled Task, so it comes back without anyone logging in and typing `wanctl start`.\n\n--name and --portal-fps are baked into the unit, because a unit restarts unattended and cannot be asked. Omit --mode so the persisted mode and portal switches survive a restart instead of being frozen at install time.",
		Params: []Param{
			{Name: "name", CLI: "--name N", Type: TypeString, CLIOnly: true, Desc: "Device name baked into the unit."},
			{Name: "portal-fps", CLI: "--portal-fps FP[,FP]", Type: TypeString, CLIOnly: true, Desc: "Portal fingerprints the agent will accept, baked into the unit."},
			{Name: "mode", CLI: "--mode M", Type: TypeString, CLIOnly: true, Desc: "Freeze the policy mode in the unit. Omit it so the persisted mode survives a restart."},
			{Name: "relay", CLI: "--relay URL", Type: TypeString, CLIOnly: true, Desc: "Relay URL baked into the unit. Defaults to the currently configured relay."},
			{Name: "transport", CLI: "--transport ws|http", Type: TypeString, CLIOnly: true, Desc: "Transport baked into the unit. Defaults to the currently configured transport."},
		},
		CLIExample: "wanctl service install --name lab-box\n  wanctl service status\n  wanctl service uninstall",
	},
	{
		Name:      "agent",
		IndexRank: 5,
		Summary:   "Run the agent in the foreground",
		Desc:      "Run the device-side agent attached to this terminal — what `wanctl start` and the OS service spawn. Use it to watch policy decisions land in real time, or under your own supervisor.",
		Params: []Param{
			{Name: "name", CLI: "--name N", Type: TypeString, CLIOnly: true, Desc: "Display name for this device. Defaults to the hostname; it does not change the device ID."},
			{Name: "relay", CLI: "--relay URL", Type: TypeString, CLIOnly: true, Desc: "Relay URL. Defaults to the configured one."},
			{Name: "token", CLI: "--token T", Type: TypeString, CLIOnly: true, Desc: "Access or registration token. Defaults to WANCTL_TOKEN, then the stored token."},
			{Name: "transport", CLI: "--transport ws|http", Type: TypeString, CLIOnly: true, Desc: "Transport to the relay. http is proxy-agnostic and works through ordinary reverse proxies."},
			{Name: "mode", CLI: "--mode normal|bypass", Type: TypeString, CLIOnly: true, Desc: "Policy mode. normal prompts on a rule miss; bypass auto-allows and is DANGEROUS. Empty keeps the last persisted mode."},
			{Name: "shell", CLI: "--shell S", Type: TypeString, CLIOnly: true, Desc: "Shell for exec. Defaults to powershell on Windows and /bin/sh elsewhere."},
			{Name: "yes", CLI: "--yes", Type: TypeBool, CLIOnly: true, Desc: "Auto-trust new controllers. For unattended devices only: it removes the human approval step."},
			{Name: "portal-fps", CLI: "--portal-fps FP[,FP]", Type: TypeString, CLIOnly: true, Desc: "Comma-separated portal admin fingerprints to seed locally, so this device accepts that portal's approvals."},
			{Name: "managed", CLI: "--managed", Type: TypeBool, CLIOnly: true, Desc: "The agent is owned by an external supervisor, so it does not try to restart itself."},
		},
		CLIExample: "wanctl agent --name lab-box --relay https://relay.example.com",
	},
	{
		Name:    "update",
		Summary: "Replace this binary with the latest signed release",
		Desc:    "Fetch the release manifest, verify the signature and swap this binary in place. A running agent keeps its pid across the swap, so systemd, launchd and `wanctl status` still point at it. Development builds are never replaced.\n\nOn Android the APK cannot be installed by the binary, so --fetch-apk downloads and verifies it and prints the path for the app to install.",
		Params: []Param{
			{Name: "fetch-apk", CLI: "--fetch-apk DIR", Type: TypeString, CLIOnly: true, Desc: "Android only. Download and verify the APK into this directory, print its path and exit. The binary cannot install an APK; the app does that with the printed path."},
			{Name: "no-restart", CLI: "--no-restart", Type: TypeBool, CLIOnly: true, Desc: "Internal. Skips the daemon stop/start, used by the sudo-elevated second phase of an update."},
		},
		CLIExample: "wanctl update\n  wanctl update --fetch-apk /sdcard/Download",
	},
	{
		Name:       "version",
		Summary:    "Print the release version",
		Desc:       "Print the immutable release version baked into this binary, or `dev` for a local build.",
		CLIExample: "wanctl version",
	},
	{
		Name:    "mcp",
		Summary: "Run wanctl as an MCP server",
		Desc:    "Serve the tools in this contract over the Model Context Protocol.\n\nWith no flags it speaks stdio: one process per AI host, single user, backed by this machine's wanctl config. With --http it serves Streamable HTTP for many users at once, deriving a separate controller identity per namespace from WANCTL_MCP_SEED; wanctl_push and wanctl_pull are withdrawn there, because `local` would name a path on the server rather than on the caller's machine.",
		Params: []Param{
			{Name: "http", CLI: "--http ADDR", Type: TypeString, CLIOnly: true, Desc: "Serve Streamable HTTP on this address (e.g. :8081) instead of stdio. Multi-user: each session derives its own controller identity from WANCTL_MCP_SEED, and wanctl_push/wanctl_pull are withdrawn because 'local' would name a path on the server."},
		},
		CLIExample: "wanctl mcp\n  wanctl mcp --http :8081",
	},
	{
		Name:    "docs",
		Summary: "Read and write the portal's documentation articles",
		Desc:    "List, read, create, edit and remove the articles the portal serves, and the groups they sit in. Bodies come from --file, from $EDITOR with --editor, or from stdin.",
		Params: []Param{
			{Name: "slug", CLI: "--slug S", Type: TypeString, CLIOnly: true, Desc: "URL slug, unique across articles."},
			{Name: "title", CLI: "--title T", Type: TypeString, CLIOnly: true, Desc: "Human title."},
			{Name: "group", CLI: "--group G", Type: TypeString, CLIOnly: true, Desc: "Group slug: a filter for `docs ls`, the destination for `docs new` and `docs edit`."},
			{Name: "position", CLI: "--position N", Type: TypeString, CLIOnly: true, Desc: "Sort order within the group."},
			{Name: "file", CLI: "--file F", Type: TypeString, CLIOnly: true, Desc: "Read the body from this local file. Without it, and without --editor, the body is read from stdin."},
			{Name: "editor", CLI: "--editor", Type: TypeBool, CLIOnly: true, Desc: "Open $EDITOR to write the body."},
		},
		CLIExample: "wanctl docs ls --group quickstart\n  wanctl docs get enroll-device\n  wanctl docs edit enroll-device --file ./enroll.md",
	},
	{
		Name:       "friends",
		Summary:    "List and manage friend relationships between namespaces",
		Desc:       "Sharing a device is only possible between namespaces that have agreed to it, so a friendship is the prerequisite for `wanctl share`. This lists relationships and pending requests, and sends, accepts, declines or removes them.",
		CLIExample: "wanctl friends\n  wanctl friends add other-ns\n  wanctl friends accept other-ns",
	},
	{
		Name:    "share",
		Summary: "Grant another namespace the use of one of your devices",
		Desc:    "Sharing hands a friend the use of a device, not ownership of it: they drive it under your device's policy, and --manage additionally lets them change that policy. Revoking takes effect on their next call.",
		Params: []Param{
			{Name: "device", CLI: "--device DEV", Type: TypeString, CLIOnly: true, Desc: "The device of yours being shared."},
			{Name: "to", CLI: "--to NS", Type: TypeString, CLIOnly: true, Desc: "The friend namespace receiving it. They must already be a friend."},
			{Name: "manage", CLI: "--manage", Type: TypeBool, CLIOnly: true, Desc: "Also let them administer the device \u2014 approvals, rules and mode \u2014 not just use it."},
		},
		CLIExample: "wanctl share grant --device home-pc --to other-ns\n  wanctl share manage --device home-pc --to other-ns on\n  wanctl share revoke --device home-pc --to other-ns",
	},
	{
		Name:      "screenshot",
		MCPName:   "wanctl_screenshot",
		Group:     GroupControl,
		IndexLine: "capture a device's screen as a PNG",
		Summary:   "Capture a device's screen as a PNG",
		Desc:      "Look at what is on a device's screen. This is the harness's eyes for anything a command cannot tell you: a dialog waiting for a click, a desktop app's state, a phone mid-flow, whether the thing you just started actually came up. Works on Android (screencap through the elevation channel), macOS (screencapture), Windows (the whole virtual screen, every monitor, through .NET) and Linux (grim, gnome-screenshot or ImageMagick's import — the first one installed; if none is, the error names them so you can install one). Captures the whole screen: there is no window picker and no region.\n\nPolicy: a desktop capture is gated exactly like any other command, because it is one — a controller allowed to run commands could run the capture tool itself. On a desktop in BYPASS mode that means a capture is auto-approved like any other command, with no separate prompt — if the device's owner does not want that, the device should not be in bypass. Android is gated as an ELEVATED command, because there a capture really does need su or the device's own adb: that class needs its own rule or an approval, unless the phone is BOTH in bypass mode and has its elevation channel switched on, in which case it is auto-approved like any other command. Same pairing and identity rules as wanctl_exec: 'PAIRING REQUIRED' carries a URL to relay VERBATIM to the user, and 'DEVICE IDENTITY CONFIRMATION REQUIRED' means call wanctl_trust_server with the target and fingerprint it gives you, then retry.",
		MCPNote:   "The PNG comes back as image content, with a line of text giving its dimensions and size. Captures over 4 MiB are downscaled to fit — the text line says so and names the format — because the point is for you to SEE the screen, not to archive it. If you need the original bytes, capture to a file on the device with wanctl_exec and fetch it.",
		CLINote:   "`screencap -p` writes a PNG to stdout, and through a shell pipeline stdout is a terminal — a screenful of binary. The CLI writes a file instead, and only writes to stdout when explicitly asked with `-o -`.",
		Params: []Param{
			{Name: "target", CLI: "[DEVICE] | --target NS/DEV", Type: TypeString, Required: true, Desc: "Device ID or unique name/alias (DEVICE|ALIAS), or NS/DEVICE|NS/ALIAS for shared devices. On the CLI it may also be the first positional argument."},
			{Name: "o", CLI: "-o FILE", Type: TypeString, CLIOnly: true, Desc: "Local file to write. Defaults to screenshot-<device>-<time>.png; \"-\" writes the PNG to stdout instead, which is the only way to pipe it."},
			{Name: "via", CLI: "--via su|adb", Type: TypeString, Desc: "Android only: pin the elevation channel, 'su' (rooted device) or 'adb' (the device's own wireless debugging). Default empty lets the device pick, and it is ignored by a desktop, which needs no channel."},
		},
		CLIExample: "wanctl screenshot home-phone -o ./screen.png",
		MCPExample: "wanctl_screenshot{\"target\":\"home-pc\"}",
		Handler:    "mcpScreenshot",
		Errors: []Failure{
			{Text: "PAIRING REQUIRED", Means: "The device has not approved this controller yet. The message carries a URL valid for 5 minutes; give it to the user verbatim, ask them to open it and approve, then retry."},
			{Text: "DEVICE IDENTITY CONFIRMATION REQUIRED", Means: "First contact with this device: nothing was sent. Pin what it presented (`wanctl trust server --target \u2026 --fingerprint \u2026`, or the wanctl_trust_server tool) and retry."},
			{Text: "command denied by device policy", Means: "The device has not allowed this controller to capture its screen. Ask the owner to approve the pending request, then retry. On Android the refusal names an ELEVATED command, which needs its own exec-elevated rule or an approval; bypass mode alone covers it only on a phone whose elevation channel is also switched on."},
			{Text: "no screen capture tool on this device", Means: "A Linux device with none of grim / gnome-screenshot / import installed. Install one (the message names them) — retrying will not help."},
			{Text: "screencapture failed: … create image from display", Means: "macOS withheld the screen: the agent has no Screen Recording permission. Open System Settings → Privacy & Security → Screen Recording on that Mac, add the wanctl binary (or the app that launched the agent), turn it on, then restart the agent — retrying without that will not help."},
			{Text: "did not return a PNG", Means: "The device answered with something else, usually an agent too old for desktop capture. Run `wanctl update` on it, then retry."},
		},
	},
	{
		Name:       "config",
		Summary:    "Show or persist relay, portal and transport settings",
		Desc:       "Show the effective settings and where each came from — a flag, an environment variable, the config file or a value baked into the build — then persist or remove the file-backed ones.",
		CLIExample: "wanctl config\n  wanctl config set relay=https://relay.example.com\n  wanctl config unset portal",
	},
	{
		Name:       "label",
		Summary:    "Show or set this controller's self-description",
		Desc:       "A device refuses to raise a pairing request from a controller that has not said who it is, because the approval screen would otherwise ask a human to trust an anonymous fingerprint.",
		CLIExample: "wanctl label \"Lin's laptop, Claude Code\"",
	},
	{
		Name:    "admin",
		Summary: "Mint, list and revoke admission invites",
		Desc:    "Instance administration for an invite-only relay. Needs WANCTL_ADMIN_SECRET; --github pre-approves a GitHub login instead of minting a code to hand out.",
		Params: []Param{
			{Name: "github", CLI: "--github LOGIN", Type: TypeString, CLIOnly: true, Desc: "Pre-approve this GitHub login instead of minting a code to hand out."},
		},
		CLIExample: "wanctl admin invite --github octocat\n  wanctl admin invites\n  wanctl admin invite-revoke INVITE-ID",
	},
	{
		Name:    "portal-admins",
		Summary: "Manage the local portal root fingerprints",
		Desc:    "The fingerprints this machine accepts as the portal's own identity. Adding one is what lets a self-hosted portal approve pairings for this device.",
		Params: []Param{
			{Name: "fingerprints", CLI: "--fingerprints FP[,FP]", Type: TypeString, CLIOnly: true, Desc: "Comma-separated SHA256 fingerprints to add or remove."},
		},
		CLIExample: "wanctl portal-admins list\n  wanctl portal-admins add SHA256:…",
	},
	{
		Name:    "relay",
		Summary: "Run the relay (the public broker)",
		Desc:    "Run the server side that brokers byte pipes between controllers and devices. It authenticates tokens and authorizes connections but cannot decrypt a session: controllers and devices speak mutual TLS through the pipe, so the relay sees ciphertext. Needs DATABASE_URL or WANCTL_TOKENS.",
		Params: []Param{
			{Name: "addr", CLI: "--addr :PORT", Type: TypeString, CLIOnly: true, Desc: "Listen address. Default :8080."},
		},
		CLIExample: "wanctl relay --addr :8080",
	},
	{
		Name:    "portal",
		Summary: "Run the web portal",
		Desc:    "Run the web front end for login, enrollment, approvals and documentation. It has no database of its own; it authenticates users and scopes calls to the relay's admin API. Logs in with GitHub OAuth, or behind a trusted SSO reverse proxy.",
		Params: []Param{
			{Name: "addr", CLI: "--addr :PORT", Type: TypeString, CLIOnly: true, Desc: "Listen address. Default :8080."},
		},
		CLIExample: "wanctl portal --addr :8080",
	},
	{
		Name:       "help",
		Summary:    "Print this contract",
		Desc:       "With no argument, print the command index. With a command name — either spelling, `read` or `wanctl_read` — print that command's full entry: summary, description, parameters, an example per surface and the error texts to react to. With --markdown, print the whole catalog, which is what docs/contract.md contains.",
		CLIExample: "wanctl help exec\n  wanctl help wanctl_read\n  wanctl help --markdown > docs/contract.md",
	},
}
